<?
$this->headTitle('Учет перевозок');
$this->placeholder('page-header')->set("Учет перевозок");
$this->headScript()->appendFile('https://cdn.jsdelivr.net/npm/free-jqgrid@4.15.5/js/jquery.jqgrid.src.min.js');
$this->headScript()->appendFile('https://cdnjs.cloudflare.com/ajax/libs/free-jqgrid/4.15.5/i18n/min/grid.locale-ru.js');
$this->headLink()->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/themes/redmond/jquery-ui.min.css');
?>
<style>
    .ui-jqgrid .ui-jqgrid-htable th div {
        height: auto;
        overflow: hidden;
        padding-top: 2px;
        padding-bottom: 2px;
        white-space: normal !important;
        font-size: 12px !important;
    }
    .ui-jqgrid .ui-row-ltr, .ui-jqgrid .ui-row-rtl {
        font-size: 12px !important;
    }
    .ui-jqgrid .ui-search-input {
        height: 30px !important;
        font-size: 15px !important;
        text-align: left;
    }
</style>
<div class="row">
    <form method="get">
        <div class="form-group float-lg-left float-md-left mr-lg-3 mr-md-3">
            <label for="year_id">Год</label>
            <div>
                <select class="chosen-select form-control" id="year_id" name="year_id" data-placeholder="Выберите из списка..." style="width: 150px;">
                    <option value="0"> </option>
                    <?
                    foreach ($this->year_row as $value){?>
                        <option value="<?=$value['year_id']?>" <?=is_selected_html($this->year_id, $value['year_id'])?>><?=$value['year_value']?></option>
                        <?
                    }?>
                </select>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="form-group float-lg-left float-md-left mr-lg-3 mr-md-3">
            <label for="month_id">Месяц</label>
            <div>
                <select class="chosen-select form-control" id="month_id" name="month_id" data-placeholder="Выберите из списка..." style="width: 150px;">
                    <option value="0"> </option>
                    <?
                    foreach ($this->month_row as $value){?>
                        <option value="<?=$value['month_id']?>" <?=is_selected_html($this->month_id, $value['month_id'])?>><?=$value['month_name']?></option>
                        <?
                    }?>
                </select>
            </div>
            <div class="clearfix"></div>
        </div>
        <button type="submit" class="btn btn-primary small-caps btn-height float-left mr-3 mt-lg-4 mt-md-4 mb-2" style="margin-top: 24px !important;">
            <i class="ace-icon fa fa-search bigger-125"></i>
            Поиск
        </button>
        <a href="<?=$this->url()?>" class="btn btn-danger small-caps btn-height float-left mr-3 mt-lg-4 mt-md-4 mb-2" style="margin-top: 24px !important;">
            <i class="ace-icon fa fa-refresh bigger-125"></i>
            Сбросить
        </a>
    </form>
    <div style="width: 99%;">
        <table id="grid"></table>
        <div id="pager"></div>
    </div>
</div>
<div class="clearfix"></div>

<script>
    $(document).ready(function () {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });

        $("#grid").jqGrid({
            datatype: "local",
            data: <?=json_encode($this->row)?>,
            colModel: [
                {
                    name: 'actions',
                    width: 170,
                    fixed: true,
                    search: false,
                    label: 'Действия',
                    formatter: function(cellvalue, options, rowObject) {
                        console.log(options, rowObject)
                        return '<button class="btn btn-sm btn-outline-primary mr-1 openNewTab" data-url="/cargo/down-list/cargo_id/'+ rowObject.cargo_id + '">Простои</button>'
                            + '<button class="btn btn-sm btn-outline-primary openNewTab" data-url="/cargo/tax-list/cargo_id/'+ rowObject.cargo_id + '">Налоги</button>';
                    }
                },
                { name: 'cargo_id', width: 100, fixed: true, align: 'right', label: 'ID', frozen: true, searchoptions: { sopt: ['cn'] } },
                { name: 'client_name', width: 170, align: 'left', fixed: true, label: 'Клиент', frozen: true, searchoptions: { sopt: ['cn'] } },
                { name: 'wagon_type_name', width: 130, align: 'left', fixed: true, label: 'Род ПС', frozen: true, searchoptions: { sopt: ['cn'] } },
                { name: 'nomer', width: 100, align: 'left', fixed: true, label: 'Номер вагона', searchoptions: { sopt: ['cn'] } },
                { name: 'station_from_name', width: 130, align: 'left', fixed: true, label: 'Станция отправления', searchoptions: { sopt: ['cn'] } },
                { name: 'route_from_name', width: 90, align: 'left', fixed: true, label: 'Дорога отправления', searchoptions: { sopt: ['cn'] } },
                { name: 'shipper_from_name', width: 220, align: 'left', fixed: true, label: 'Грузоотправитель', searchoptions: { sopt: ['cn'] } },
                { name: 'date_arrival', width: 150, align: 'center', fixed: true, label: 'Дата прибытия', searchoptions: { sopt: ['cn'] } },
                { name: 'date_departure', width: 150, align: 'center', fixed: true, label: 'Дата отправления', searchoptions: { sopt: ['cn'] } },
                { name: 'duration', width: 100, align: 'right', fixed: true, label: 'Простой на погрузке', searchoptions: { sopt: ['cn'] } },
                { name: 'date_issue', width: 150, align: 'center', fixed: true, label: 'Дата оформления', searchoptions: { sopt: ['cn'] } },
                { name: 'document_num', width: 130, align: 'left', fixed: true, label: 'Накладн.', searchoptions: { sopt: ['cn'] } },
                { name: 'station_to_name', width: 140, align: 'left', fixed: true, label: 'Станция назначения', searchoptions: { sopt: ['cn'] } },
                { name: 'route_to_name', width: 100, align: 'left', fixed: true, label: 'Дорога назначения', searchoptions: { sopt: ['cn'] } },
                { name: 'shipper_to_name', width: 220, align: 'left', fixed: true, label: 'Грузополучатель', searchoptions: { sopt: ['cn'] } },
                { name: 'date_arrival_next', width: 150, align: 'center', fixed: true, label: 'Дата прибытия', searchoptions: { sopt: ['cn'] } },
                { name: 'date_departure_next', width: 150, align: 'center', fixed: true, label: 'Дата отправления', searchoptions: { sopt: ['cn'] } },
                { name: 'next_duration', width: 100, align: 'right', fixed: true, label: 'Простой на выгрузке', searchoptions: { sopt: ['cn'] } },
                { name: 'distance', width: 100, align: 'right', fixed: true, label: 'Расстояние', searchoptions: { sopt: ['cn'] } },
                { name: 'good_name', width: 240, align: 'left', fixed: true, label: 'Груз', searchoptions: { sopt: ['cn'] } },
                { name: 'good_weight', width: 100, align: 'right', fixed: true, label: 'Вес', searchoptions: { sopt: ['cn'] } },
                { name: 'tariff_client_nds', width: 180, align: 'right', fixed: true, label: 'Ставка клиента с учетом НДС, рублей', searchoptions: { sopt: ['cn'] } },
                { name: 'tariff_client_tenge', width: 180, align: 'right', fixed: true, label: 'Ставка клиента с учетом НДС, тенге', searchoptions: { sopt: ['cn'] } },
                { name: 'transport_type', width: 120, align: 'left', fixed: true, label: 'Вид перевозки (внутренняя/экспорт)', searchoptions: { sopt: ['cn'] } },
                { name: 'provider_name', width: 100, align: 'left', fixed: true, label: 'Поставщик', searchoptions: { sopt: ['cn'] } },
                { name: 'tariff_provider_nds', width: 200, align: 'right', fixed: true, label: 'Ставка поставщика с учетом НДС, тенге', searchoptions: { sopt: ['cn'] } },
                { name: 'tariff_provider_tenge', width: 200, align: 'right', fixed: true, label: 'Ставка поставщика с учетом НДС, рублей', searchoptions: { sopt: ['cn'] } },
                { name: 'rate', width: 100, fixed: true, align: 'right', label: 'Курс валют на момент оплаты поставщику (тенге за рубль)', searchoptions: { sopt: ['cn'] } },
                { name: 'economika_rub', width: 150, fixed: true, align: 'right', label: 'ЭКОНОМИКА (предварительный итог), рублей', searchoptions: { sopt: ['cn'] } },
                { name: 'economika_tenge', width: 150, fixed: true, align: 'right', label: 'ЭКОНОМИКА (предварительный итог), тенге', searchoptions: { sopt: ['cn'] } },
            ],
            pager: '#pager',
            autowidth: true,
            shrinkToFit: false,
            height: $(document).height()-420,
            rowNum: 500,
            viewrecords: true,
            ignoreCase: true,
            loadonce: true,
            rownumbers: true,
        });

        $("#grid").jqGrid('filterToolbar');
        $("#grid").jqGrid('navGrid', '#pager', { search: false, add: false, edit: false, del: false, rownumbers: true});

        $(window).on('resize', function () {
            var newWidth = $("#grid").closest('.ui-jqgrid').parent().width();
            $("#grid").jqGrid('setGridWidth', newWidth, true);
        }).trigger('resize');

        $(document).on('click', '.openNewTab', function() {
            var url = $(this).data('url');
            window.open(url, '_blank');
        });
    });
</script>
