<?
$this->headTitle('ПСЦ + простои ('. $this->row_client['client_name'].')');
$this->placeholder('page-header')->set('ПСЦ + простои ('. $this->row_client['client_name'].')');
?>
<div class="row">
    <div class="bcard p-3" id="load">
        <div id="tab">
            <div class="table-responsive">
                <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top" id="employee_table">
                    <thead>
                    <tr>
                        <th class="text-center">Порядковый номер</th>
                        <th class="text-center">Номер вагона</th>
                        <th class="text-center" colspan="2">Направление</th>
                        <th class="text-center">Дата прибытия на станцию погрузки</th>
                        <th class="text-center">Дата отправления со станции погрузки</th>
                        <th class="text-center">Простой на погрузке, сут</th>
                        <th class="text-center">Дата прибытия на станцию выгрузки</th>
                        <th class="text-center">Дата отправления со станции выгрузки</th>
                        <th class="text-center">Простой на выгрузке, сут</th>
                        <th class="text-center">Сверхнормативный простой по ПСЦ на погрузке, сут</th>
                        <th class="text-center">Сверхнормативный простой по ПСЦ на выгрузке, сут</th>
                        <th class="text-center">Величина штрафа, руб</th>
                        <th class="text-center">Сумма штрафов за сверхнормативный простой</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?
                    if (mycount($this->row) > 0) {
                        $i = 0;
                        $sum = 0;
                        foreach ($this->row as $key => $value) {
                            $i++;
                            $sum += $value['penalty_sum'];
                            ?>
                            <tr>
                                <td class="text-right"><?=$i?></td>
                                <td class="text-left"><?=$value['nomer']?></td>
                                <td class="text-left"><?=$value['station_from_name']?></td>
                                <td class="text-left"><?=$value['station_to_name']?></td>
                                <td class="text-center"><?=$value['date_arrival']?></td>
                                <td class="text-center"><?=$value['date_departure']?></td>
                                <td class="text-right"><?=$value['duration']?></td>
                                <td class="text-center"><?=$value['date_arrival_next']?></td>
                                <td class="text-center"><?=$value['date_departure_next']?></td>
                                <td class="text-right"><?=$value['next_duration']?></td>
                                <td class="text-right"><?=$value['norm_from']?></td>
                                <td class="text-right"><?=$value['norm_to']?></td>
                                <td class="text-right"><?=tenge_text($value['penalty_rub'])?></td>
                                <td class="text-right"><?=tenge_text($value['penalty_sum'])?></td>
                            </tr>
                            <?
                        }
                    }
                    ?>
                    <tr>
                        <td colspan="13" class="text-right"><b>Итого:</b></td>
                        <td class="text-right"><?=tenge_text($sum)?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
    });
</script>