<?
$this->headTitle('Налоги ('. $this->row_client['client_name'].')');
$this->placeholder('page-header')->set('Налоги ('. $this->row_client['client_name'].')');
?>
<div class="row">
    <div class="bcard p-3" id="load">
        <div id="tab">
            <div class="table-responsive">
                <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top" id="employee_table">
                    <thead>
                    <tr>
                        <th class="text-center">№ п/п</th>
                        <th class="text-center">Станция отправления</th>
                        <th class="text-center">Дорога отправления</th>
                        <th class="text-center">Станция назначения</th>
                        <th class="text-center">Дорога назначения</th>
                        <th class="text-center">Дата отгрузки</th>
                        <th class="text-center">Накладная</th>
                        <th class="text-center">Номер вагона</th>
                        <th class="text-center">Груз</th>
                        <th class="text-center">Стоимость услуг исполнителя, в рублях</th>
                        <th class="text-center">Ставка КТТ, в рублях</th>
                        <th class="text-center">Комиссия</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?
                    if (mycount($this->row) > 0) {
                        $i = 0;
                        $sum_client = 0;
                        $sum_provider = 0;
                        $sum_comission = 0;
                        foreach ($this->row as $key => $value) {
                            $i++;
                            $sum_client += $value['tariff_client_nds'];
                            $sum_provider += $value['tariff_provider_nds'];
                            $sum_comission += $value['comission'];
                            ?>
                            <tr>
                                <td class="text-right"><?=$i?></td>
                                <td class="text-left"><?=$value['station_from_name']?></td>
                                <td class="text-left"><?=$value['route_from_name']?></td>
                                <td class="text-left"><?=$value['station_to_name']?></td>
                                <td class="text-left"><?=$value['route_to_name']?></td>
                                <td class="text-center"><?=$value['date_arrival']?></td>
                                <td class="text-left"><?=$value['document_num']?></td>
                                <td class="text-left"><?=$value['nomer']?></td>
                                <td class="text-left"><?=$value['good_name']?></td>
                                <td class="text-right"><?=tenge_text($value['tariff_client_nds'])?></td>
                                <td class="text-right"><?=tenge_text($value['tariff_provider_nds'])?></td>
                                <td class="text-right"><?=tenge_text($value['comission'])?></td>
                            </tr>
                            <?
                        }
                    }
                    ?>
                    <tr>
                        <td colspan="9" class="text-right"><b>Итого:</b></td>
                        <td class="text-right"><?=tenge_text($sum_client)?></td>
                        <td class="text-right"><?=tenge_text($sum_provider)?></td>
                        <td class="text-right"><?=tenge_text($sum_comission)?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
    });
</script>