<?
$this->headTitle('Все платежи');
$this->placeholder('page-header')->set("Все платежи");
?>

<div class="hr hr-10 dotted hr-double"></div>
<div class="row">
    <form method="get" class="float-left" style="margin-bottom: 10px;">
        <div class="form-group float-left mr-2" style="width: 150px;">
            <label class="control-label no-padding-right" for="date_begin">Дата с</label>
            <input type="text" id="date_begin" name="date_begin" style="width: 150px; height: 35px;" placeholder="Дата с" class="form-control date-picker" autocomplete="off" value="<?=$this->date_begin?>">
        </div>
        <div class="form-group float-left mr-2" style="width: 150px;">
            <label class="control-label no-padding-right" for="date_end">Дата по</label>
            <input type="text" id="date_end" name="date_end" style="width: 150px; height: 35px;" placeholder="Дата по" class="form-control date-picker" autocomplete="off" value="<?=$this->date_end?>">
        </div>
        <div class="float-left mr-2">
            <label for="payment_status">Статус</label>
            <div>
                <select class="chosen-select form-control" id="payment_status" name="payment_status" data-placeholder="Выберите из списка..." style="width: 150px;">
                    <option value="-1"> Все</option>
                    <option value="1" <?=is_selected_html($this->payment_status, '1')?>> Создан</option>
                    <option value="2" <?=is_selected_html($this->payment_status, '2')?>> Отклонен</option>
                    <option value="3" <?=is_selected_html($this->payment_status, '3')?>> Оплачен</option>
                </select>
            </div>
            <div class="clearfix"></div>
        </div>
        <button type="submit" name="search_employee" class="btn btn-primary float-left" style="margin-top: 24px;">
            <i class="ace-icon fa fa-search bigger-125"></i>
            Поиск
        </button>
        <div class="clearfix"></div>
    </form>
    <div class="clearfix"></div>
    <div class="col-lg-12 p-0" id="load">
        <div class="card dcard mb-3" id="shop_table" draggable="false" style="">
            <div class="card-body p-0">
                <div class="p-3">
                    <div class="card-body p-0 table-responsive">
                        <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
                            <thead>
                            <tr>
                                <th>ID заявки</th>
                                <th>Заявка</th>
                                <th>Тип платежа</th>
                                <th>Сумма</th>
                                <th>Статус</th>
                                <th>Комментарий</th>
                                <th>Работник</th>
                                <th>Дата создания</th>
                                <th>Вложения</th>
                                <th>Действия</th>
                                <th>Удалить</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?
                            if(mycount($this->row) > 0){
                                $i = 1;
                                foreach ($this->row as $key => $value){
                                    $status_color = '#e19e2e69';
                                    if($value['status_text'] == 'Оплачен'){
                                        $status_color = '#36ad8282';
                                    }
                                    if($value['status_text'] == 'Отклонен'){
                                        $status_color = '#e12e2e69';
                                    }
                                    ?>
                                    <tr>
                                        <td class="text-right"><?=$value['client_request_id']?></td>
                                        <td class="text-left"><a href="/work/client-request-edit/client_request_id/<?=$value['client_request_id']?>/" target="_blank"><?=$value['client_request']?></a></td>
                                        <td class="text-left"><?=$value['payment_type_name']?></td>
                                        <td class="text-center"><?=tenge_text($value['payment_sum'])?>тг</td>
                                        <td class="text-left" style="background-color: <?=$status_color?>"><?=$value['status_text']?></td>
                                        <td class="text-left"><?=$value['payment_comment']?></td>
                                        <td class="text-left"><?=$value['fio']?></td>
                                        <td class="text-center"><?=$value['date_create']?></td>
                                        <td class="text-center">
                                            <?if(strlen($value['payment_url']) > 0){?>
                                                <div class="action-buttons">
                                                    <a href="<?=$value['payment_url']?>" style="font-size: 10px;" title="Скачать" class="btn btn-xs btn-secondary" target="_blank" download="download">
                                                        <i class="fa fa-download" aria-hidden="true">
                                                        </i> Скачать
                                                    </a>
                                                </div>
                                                <?
                                            }?>
                                        </td>
                                        <td class="text-center">
                                            <?if($value['payment_status'] == 1){?>
                                                <div class="action-buttons">
                                                    <a class="btn btn-xs btn-warning" href="javascript:void(0);" style="font-size: 10px;" onclick="statusPayment(<?=$value['payment_id']?>, 2, this)">
                                                        <i class="fa fa-ban" aria-hidden="true">
                                                        </i>  Отклонить
                                                    </a>
                                                    <a class="btn btn-xs btn-success" href="javascript:void(0);" style="font-size: 10px;" onclick="statusPayment(<?=$value['payment_id']?>, 3, this)">
                                                        <i class="fa fa-check" aria-hidden="true">
                                                        </i>  Оплачен
                                                    </a>
                                                </div>
                                                <?
                                            }?>
                                            <?if($value['payment_status'] != 1 && getCurPositionCode() == 'ADMIN'){?>
                                                <div class="action-buttons">
                                                    <a class="btn btn-xs btn-grey" href="javascript:void(0);" style="font-size: 10px;" onclick="statusPayment(<?=$value['payment_id']?>, 1, this)">
                                                        <i class="fa fa-ban" aria-hidden="true">
                                                        </i>  Сбросить
                                                    </a>
                                                </div>
                                                <?
                                            }?>
                                        </td>
                                        <td class="text-center">
                                            <div class="action-buttons">
                                                <a class="btn btn-xs btn-danger" href="javascript:void(0);" style="font-size: 10px;" onclick="delPayment(<?=$value['payment_id']?>, this)">
                                                    <i class="fa fa-trash" aria-hidden="true">
                                                    </i>  Удалить
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <?
                                    $i = $i + 1;
                                }
                            }
                            ?>
                            </tbody>
                        </table>
                    </div><!-- /.card-body -->
                </div>
            </div><!-- /.card-body -->
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $(".datepicker").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-100:+0"
        });
    });

    function delPayment(payment_id, ob){
        if (!confirm("Вы действительно хотите удалить платеж ?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/work/client-request-edit/mode/del-payment/payment_id/" + payment_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Платеж удален');
                    $(ob).closest("tr").remove();
                }
            }
        });
    }
    function statusPayment(payment_id, payment_status, ob){
        if (!confirm("Вы действительно хотите изменить статус?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/work/client-request-edit/mode/upd-payment-status/payment_id/" + payment_id + "/payment_status/" + payment_status + "/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Статус изменен');
                    location.reload();
                }
            }
        });
    }
</script>