<div class="modal-body" id="modal_body">
    <form id="form_id">
        <input type="hidden" value="<?=$this->client_request_id?>" name="client_request_id">

        <div class="form-group">
            <label class="control-label " for="client_fio">ФИО</label>
            <input type="text" id="client_fio" placeholder="ФИО" class="form-control" value="<?=$this->row['client_fio'] ?? null?>" name="client_fio">
            <div class="clearfix"></div>
        </div>

        <div class="form-group">
            <label class="control-label " for="client_iin">ИИН</label>
            <input type="text" id="clieclient_iinnt_fio" placeholder="ИИН" class="form-control iin" value="<?=$this->row['client_iin'] ?? null?>" name="client_iin">
            <div class="clearfix"></div>
        </div>

        <div class="form-group">
            <label class="control-label " for="client_doc_num">Номер удв.</label>
            <input type="text" id="client_doc_num" placeholder="Номер удв." class="form-control iin" value="<?=$this->row['client_doc_num'] ?? null?>" name="client_doc_num">
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="client_doc_source">Орган выдачи удв.</label>
            <input type="text" id="client_doc_source" placeholder="Орган выдачи удв." class="form-control" value="<?=$this->row['client_doc_source'] ?? null?>" name="client_doc_source">
            <div class="clearfix"></div>
        </div>

        <div class="form-group">
            <label class="control-label " for="client_phone">Телефон</label>
            <input type="text" id="client_phone" placeholder="Телефон" class="form-control" value="<?=$this->row['client_phone'] ?? null?>" name="client_phone">
            <div class="clearfix"></div>
        </div>

        <div class="form-group">
            <label class="control-label " for="address">Адрес</label>
            <input type="text" id="address" placeholder="Адрес" class="form-control" value="<?=$this->row['address'] ?? null?>" name="address">
            <div class="clearfix"></div>
        </div>

        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-sm px-4 btn-outline-success mb-1" onclick="updClient()">Сохранить</button>
    <button type="button" class="btn btn-sm px-4 btn-outline-danger mb-1" data-dismiss="modal">Закрыть</button>
</div>

<script>
    $(document).ready(function() {
        $("#client_phone").inputmask("+7(999) 999-9999");
        $(".iin").inputmask("999999999999");
    });

    function updClient(){
        main_loader_show();
        var send_data = new FormData($("#form_id")[0]);

        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/work/client-request-edit/mode/upd-client/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    $('.modal').modal('hide');
                    toastSucces('Успех');
                    location.reload();
                }
                main_loader_hide();
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }
</script>