<?
$this->headTitle('Заявка №'.$this->client_request_id);
$this->placeholder('page-header')->set('Заявка №'.$this->client_request_id);
?>
<div class="row">
    <div class="col-12 col-md-12">
        <div class="alert bgc-blue-l1 text-dark-m2 border-0 text-110 mb-0 p-3">
            <div style="float:left; margin-right: 40px;">
                <p>ФИО: <?=$this->row['client_fio']?></p>
                <p>Адрес: <?=$this->row['address']?></p>
                <p>Телефон клиента: <?=$this->row['client_phone']?></p>
            </div>
            <div style="float:left; margin-right: 40px;">
                <p>Тип клиента: <?=$this->row['client_type']?></p>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
        <br>
        <div class="dcard">
            <ul class="nav nav-tabs bgc-secondary-l3 border-y-1 brc-secondary-l3" role="tablist">
                <li class="nav-item mr-2px">
                    <a id="home1-tab-btn" class="d-style active btn btn-tp btn-light-secondary btn-h-white btn-a-text-dark btn-a-white text-95 px-3 px-sm-4 py-25 radius-0 border-0" data-toggle="tab" href="#home1" role="tab" aria-controls="home1" aria-selected="true">
                        <span class="v-active position-tl w-100 border-t-3 brc-blue mt-n2px"></span>
                        Общее
                    </a>
                </li>
                <li class="nav-item mr-2px">
                    <a id="profile1-tab-btn" class="d-style btn btn-tp btn-light-secondary btn-h-white btn-a-text-dark btn-a-white text-95 px-3 px-sm-4 py-25 radius-0 border-0" data-toggle="tab" href="#wants" role="tab" aria-controls="profile1" aria-selected="false">
                        <span class="v-active position-tl w-100 border-t-3 brc-blue mt-n2px"></span>
                        Предпочтения
                    </a>
                </li>
                <li class="nav-item">
                    <a id="more1-tab-btn" class="d-style btn btn-tp btn-light-secondary btn-h-white btn-a-text-dark btn-a-white text-95 px-3 px-sm-4 py-25 radius-0 border-0" data-toggle="tab" href="#docs" role="tab" aria-controls="more1" aria-selected="false">
                        <span class="v-active position-tl w-100 border-t-3 brc-blue mt-n2px"></span>
                        Документы
                    </a>
                </li>
                <li class="nav-item">
                    <a id="more1-tab-btn" class="d-style btn btn-tp btn-light-secondary btn-h-white btn-a-text-dark btn-a-white text-95 px-3 px-sm-4 py-25 radius-0 border-0" data-toggle="tab" href="#payments" role="tab" aria-controls="more1" aria-selected="false">
                        <span class="v-active position-tl w-100 border-t-3 brc-blue mt-n2px"></span>
                        Платежи
                    </a>
                </li>
            </ul>

            <div class="tab-content bgc-white p-35 border-0">
                <div class="tab-pane fade show active text-95" id="home1" role="tabpanel" aria-labelledby="home1-tab-btn">
                    <div id="common" class="tab-pane ">
                        <div class="col-lg-3 col-md-4 col-sm-5">
                            <form id="form_request">
                                <input type="hidden" name="client_request_id" value="<?=$this->client_request_id?>">
                                <div class="form-group pull-left margin-right-10">
                                    <label class="control-label no-padding-right">Цена работы</label>
                                    <input type="number" step="any" name="total_price" placeholder="Цена работы" class="form-control" value="<?=$this->row['total_price']?>" autocomplete="off">
                                </div>
                                <div class="clearfix"></div>
                                <div class="form-group pull-left margin-right-10">
                                    <label class="control-label no-padding-right">Менеджер проекта</label>
                                    <select class="form-control" id="platform" name="mp_employee_id">
                                        <option value="0">Выберите МП</option>
                                        <?foreach ($this->row_mp as $value){?>
                                            <option value="<?=$value['employee_id']?>" <?if($value['employee_id'] == $this->row['mp_employee_id']){?>selected<?}?>><?=$value['fio']?></option>
                                            <?
                                        }?>
                                    </select>
                                </div>
                                <div class="clearfix"></div>
                                <button class="btn btn-success btn-bold px-4" type="button" onclick="upd_request()">
                                    <i class="fa fa-check mr-1"></i>
                                    Сохранить
                                </button>
                            </form>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>

                <div class="tab-pane fade text-95" id="wants" role="tabpanel" aria-labelledby="profile1-tab-btn">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <form id="form_wish">
                            <input type="hidden" name="client_request_id" value="<?=$this->client_request_id?>">
                            <div class="form-group pull-left margin-right-10">
                                <label class="control-label no-padding-right" for="measure_date">Предпочтения клиента</label>
                                <textarea id="client_comment" name="client_wants" style="height: 200px;" class="autosize-transition form-control"><?=$this->row['client_wants']?></textarea>
                            </div>
                            <button class="btn btn-success btn-bold px-4" type="button" onclick="upd_request_wish()">
                                <i class="fa fa-check mr-1"></i>
                                Сохранить
                            </button>
                        </form>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="tab-pane fade text-95" id="docs" role="tabpanel" aria-labelledby="more1-tab-btn">
                    <a href="javascript:void(0)" onclick="showDocumentForm(<?=$this->client_request_id?>)" class="btn btn-info btn-xs pull-right">Добавить</a>
                    <div class="clearfix"></div>
                    <hr>
                    <div id="documents">

                    </div>
                </div>
                
                <div class="tab-pane fade text-95" id="payments" role="tabpanel" aria-labelledby="more1-tab-btn">
                    <a href="javascript:void(0)" onclick="showPaymentForm(<?=$this->client_request_id?>)" class="btn btn-info btn-xs pull-right">Добавить</a>
                    <div class="clearfix"></div>
                    <hr>
                    <div id="payment">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $( document ).ready(function() {
        $('#documents').load('/work/document-list/client_request_id/<?=$this->client_request_id?>');
        $('#payment').load('/work/payment-list/client_request_id/<?=$this->client_request_id?>');
    });
    function upd_request(){
        var fd = new FormData($("#form_request")[0]);
        $.ajax({
            type: 'POST',
            url: "/work/client-request-edit/mode/upd/",
            data: fd,
            success: function(data){
                if(data.result['status'] == false){
                    alert(data.result['error']);
                    toastError('Ошибка при редактировании');
                } else{
                    toastSucces('Заявка отредактирована');
                    window.location.reload();
                }
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }
    function upd_request_wish(){
        var fd = new FormData($("#form_wish")[0]);
        $.ajax({
            type: 'POST',
            url: "/work/client-request-edit/mode/upd-wish/",
            data: fd,
            success: function(data){
                if(data.result['status'] == false){
                    alert(data.result['error']);
                    toastError('Ошибка при редактировании');
                } else{
                    toastSucces('Заявка отредактирована');
                    window.location.reload();
                }
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }
    function showDocumentForm(client_request_id){
        $('#modal-container').find('.modal-dialog').addClass('modal-md');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        $('#modal-header-container').append('Добавить документ');
        $.ajax({
            type: 'POST',
            url: "/work/document-edit/",
            data: {"client_request_id" : client_request_id,},
            async: true,
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $("#modal-container").filter('.modal').modal();
    }
    function showPaymentForm(client_request_id){
        $('#modal-container').find('.modal-dialog').addClass('modal-md');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        $('#modal-header-container').append('Добавить платеж');
        $.ajax({
            type: 'POST',
            url: "/work/payment-edit/",
            data: {"client_request_id" : client_request_id,},
            async: true,
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $("#modal-container").filter('.modal').modal();
    }
    function delDocument(document_id, ob){
        if (!confirm("Вы действительно хотите удалить документ ?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/work/client-request-edit/mode/del-doc/document_id/" + document_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Документ удален');
                    $(ob).closest("tr").remove();
                }
            }
        });
    }
    function delPayment(payment_id, ob){
        if (!confirm("Вы действительно хотите удалить платеж ?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/work/client-request-edit/mode/del-payment/payment_id/" + payment_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Платеж удален');
                    $(ob).closest("tr").remove();
                }
            }
        });
    }
    function statusPayment(payment_id, payment_status, ob){
        if (!confirm("Вы действительно хотите изменить статус?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/work/client-request-edit/mode/upd-payment-status/payment_id/" + payment_id + "/payment_status/" + payment_status + "/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Статус изменен');
                    $('#payments').load('/work/payment-list/client_request_id/<?=$this->client_request_id?>');
                }
            }
        });
    }
    function create_work(client_request_id){
        if (!confirm("Вы действительно хотите создать ремонт?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/work/client-request-edit/mode/create-work/client_request_id/" + client_request_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Ремонт создан');
                    window.location.href = '/work/work-edit/work_id/' + data.result['value'];
                }
            }
        });
    }
</script>