<div class="table-responsive">
    <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
        <thead>
        <tr>
            <th>ID</th>
            <th>Название</th>
            <th>Тип документа</th>
            <th>Работник</th>
            <th>Дата создания</th>
            <th>Скачать</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?
        if(mycount($this->row) > 0){
            $i = 1;
            foreach ($this->row as $key => $value){
                ?>
                <tr>
                    <td class="text-right"><?=$i?></td>
                    <td class="text-left"><?=$value['document_name']?></td>
                    <td class="text-left"><?=$value['document_type_name']?></td>
                    <td class="text-left"><?=$value['fio']?></td>
                    <td class="text-center"><?=$value['date_create']?></td>
                    <td class="text-center">
                        <div class="action-buttons">
                            <a href="<?=$value['document_url']?>" title="Скачать" class="btn btn-xs btn-secondary" target="_blank" download="download">
                                <i class="fa fa-download" aria-hidden="true">
                                </i> Скачать
                            </a>
                        </div>
                    </td>
                    <td class="text-center">
                        <div class="action-buttons">
                            <a class="btn btn-xs btn-danger" href="javascript:void(0);" onclick="delDocument(<?=$value['document_id']?>, this)">
                                <i class="fa fa-trash" aria-hidden="true">
                                </i>  Удалить
                            </a>
                        </div>
                    </td>
                </tr>
                <?
                $i = $i + 1;
            }
        }
        ?>
        </tbody>
    </table>
</div>