<div class="table-responsive">
    <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
        <thead>
        <tr>
            <th>ID</th>
            <th>Тип платежа</th>
            <th>Сумма</th>
            <th>Статус</th>
            <th>Комментарий</th>
            <th>Работник</th>
            <th>Дата создания</th>
            <th>Вложения</th>
            <th>Действия</th>
            <th>Удалить</th>
        </tr>
        </thead>
        <tbody>
        <?
        if(mycount($this->row) > 0){
            $i = 1;
            foreach ($this->row as $key => $value){
                $status_color = '#e19e2e69';
                if($value['status_text'] == 'Оплачен'){
                    $status_color = '#36ad8282';
                }
                if($value['status_text'] == 'Отклонен'){
                    $status_color = '#e12e2e69';
                }
                ?>
                <tr>
                    <td class="text-right"><?=$i?></td>
                    <td class="text-left"><?=$value['payment_type_name']?></td>
                    <td class="text-center"><?=tenge_text($value['payment_sum'])?>тг</td>
                    <td class="text-left" style="background-color: <?=$status_color?>"><?=$value['status_text']?></td>
                    <td class="text-left"><?=$value['payment_comment']?></td>
                    <td class="text-left"><?=$value['fio']?></td>
                    <td class="text-center"><?=$value['date_create']?></td>
                    <td class="text-center">
                        <?if(strlen($value['payment_url']) > 0){?>
                            <div class="action-buttons">
                                <a href="<?=$value['payment_url']?>" title="Скачать" class="btn btn-xs btn-secondary" target="_blank" download="download">
                                    <i class="fa fa-download" aria-hidden="true">
                                    </i> Скачать
                                </a>
                            </div>
                            <?
                        }?>
                    </td>
                    <td class="text-center">
                        <?if($value['payment_status'] == 1){?>
                            <div class="action-buttons">
                                <a class="btn btn-xs btn-warning" href="javascript:void(0);" onclick="statusPayment(<?=$value['payment_id']?>, 2, this)">
                                    <i class="fa fa-ban" aria-hidden="true">
                                    </i>  Отклонить
                                </a>
                                <a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="statusPayment(<?=$value['payment_id']?>, 3, this)">
                                    <i class="fa fa-check" aria-hidden="true">
                                    </i>  Оплачен
                                </a>
                            </div>
                            <?
                        }?>
                        <?if($value['payment_status'] != 1 && getCurPositionCode() == 'ADMIN'){?>
                            <div class="action-buttons">
                                <a class="btn btn-xs btn-grey" href="javascript:void(0);" onclick="statusPayment(<?=$value['payment_id']?>, 1, this)">
                                    <i class="fa fa-ban" aria-hidden="true">
                                    </i>  Сбросить
                                </a>
                            </div>
                            <?
                        }?>
                    </td>
                    <td class="text-center">
                        <div class="action-buttons">
                            <a class="btn btn-xs btn-danger" href="javascript:void(0);" onclick="delPayment(<?=$value['payment_id']?>, this)">
                                <i class="fa fa-trash" aria-hidden="true">
                                </i>  Удалить
                            </a>
                        </div>
                    </td>
                </tr>
                <?
                $i = $i + 1;
            }
        }
        ?>
        </tbody>
    </table>
</div>