<div class="table-responsive">
    <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
        <thead>
        <tr>
            <th>ID</th>
            <th>Название</th>
            <th>Финальный</th>
            <th>Утвержден</th>
            <th>Дата создания</th>
            <th>Работник</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?
        if(mycount($this->row) > 0){
            $i = 1;
            foreach ($this->row as $key => $value){
                $background = '';
                if($value['is_accepted'] == 2){
                    $background = '#fcb3b3';
                }elseif ($value['is_accepted'] == 1){
                    $background = '#befcb3';
                }
                ?>
                <tr style="background-color: <?=$background?>">
                    <td class="text-right"><?=$i?></td>
                    <td class="text-left"><?=$value['work_project_filename']?></td>
                    <td class="text-center">
                        <?if($value['is_final'] == 1){?>
                            <i class="fa fa-check text-green-m2" style="font-size: 20px;"></i>
                        <?}?>
                    </td>
                    <td class="text-center">
                        <?if($value['is_accepted'] == 1){?>
                            <i class="fa fa-check text-green-m2" style="font-size: 20px;"></i>
                            <br>
                            <?=$value['accept_fio']?> <?=$value['is_accepted_date']?>
                            <?if(getCurPositionCode() == 'ADMIN'){?>
                                <br>
                                <button class="btn btn-danger btn-xs" onclick="acceptProject(<?=$value['work_project_id']?>, 0)">Убрать</button>
                            <?}?>
                        <?}else if($value['is_accepted'] == 2){?>
                            <i class="fa fa-ban text-danger-m2" style="font-size: 20px;"></i>
                            <br>
                            <?=$value['accept_fio']?> <?=$value['is_accepted_date']?>
                            <?if(getCurPositionCode() == 'ADMIN'){?>
                                <br>
                                <button class="btn btn-danger btn-xs" onclick="acceptProject(<?=$value['work_project_id']?>, 0)">Убрать</button>
                            <?}?>
                        <?}else{?>
                            <button class="btn btn-primary btn-xs" onclick="acceptProject(<?=$value['work_project_id']?>, 1)">Утвердить</button>
                            <button class="btn btn-danger btn-xs" onclick="acceptProject(<?=$value['work_project_id']?>, 2)">Отклонить</button>
                            <?
                        }?>
                    </td>
                    <td class="text-center"><?=$value['date_create']?></td>
                    <td class="text-left"><?=$value['fio']?></td>
                    <td class="text-center">
                        <div class="action-buttons">
                            <a class="btn btn-xs btn-danger" href="javascript:void(0);" onclick="delworkProject(<?=$value['work_project_id']?>, this)">
                                <i class="fa fa-trash" aria-hidden="true">
                                </i>  Удалить
                            </a>
                            <a class="btn btn-xs btn-primary" href="javascript:void(0);" onclick="showProjectForm(<?=$value['work_id']?>, <?=$value['work_project_id']?>)">
                                <i class="fa fa-edit" aria-hidden="true">
                                </i>  Изменить
                            </a>
                            <a class="btn btn-xs btn-success" href="<?=$value['work_project_url']?>" target="_blank" download="download">
                                <i class="fa fa-download" aria-hidden="true">
                                </i>  Скачать
                            </a>
                        </div>
                    </td>
                </tr>
                <?
                $i = $i + 1;
            }
        }
        ?>
        </tbody>
    </table>
</div>