<div class="modal-body" id="modal_body">
    <form id="form_id">
        <input type="hidden" value="<?=$this->work_id?>" name="work_id">
        <input type="hidden" value="<?=$this->work_project_id?>" name="work_project_id">

        <div class="form-group">
            <label class="control-label " for="work_project_filename">Наименование</label>
            <input type="text" id="work_project_filename" placeholder="Наименование" class="form-control" value="<?=$this->row['work_project_filename'] ?? null?>" name="work_project_filename">
            <div class="clearfix"></div>
        </div>

        <label>
            <input type="checkbox" name="is_final" class="input-lg bgc-blue" checked="">
            Финальный
        </label>

        <div class="form-group">
            <label class="control-label " for="discount_percent">Файл</label>
            <div class="form-control no-padding">
                <input type="file" name="upload" id="upload" >
            </div>
            <div class="clearfix"></div>
        </div>

        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-sm px-4 btn-outline-success mb-1" onclick="updDocument()">Сохранить</button>
    <button type="button" class="btn btn-sm px-4 btn-outline-danger mb-1" data-dismiss="modal">Закрыть</button>
</div>

<script>
    $(document).ready(function() {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });
    });

    function updDocument(){
        main_loader_show();
        var send_data = new FormData($("#form_id")[0]);

        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/work/work-edit/mode/upd-project/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    $('.modal').modal('hide');
                    toastSucces('Успех');
                    $('#project_list').load('/work/work-project-list/work_id/<?=$this->work_id?>');
                }
                main_loader_hide();
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }
</script>