<?
$stage_name = 'Замер/Проектирование';
if($this->stage_id == 2){
    $stage_name = 'Смета/Закуп';
}elseif ($this->stage_id == 3){
    $stage_name = 'Цех';
}elseif ($this->stage_id == 4){
    $stage_name = 'Доставка/Монтаж';
}elseif ($this->stage_id == 5){
    $stage_name = 'Сдача клиенту';
}

$this->headTitle('Заказы - '.$stage_name.'('.mycount($this->row).')');
$this->placeholder('page-header')->set('Заказы - '.$stage_name.'('.mycount($this->row).')');
?>
<div class="hr hr-10 dotted hr-double"></div>
<div class="bcard p-3" id="load">
    <div id="tab">
        <div class="table-responsive">
            <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top" id="employee_table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Адрес</th>
                    <th>Тип клиента</th>
                    <th>ФИО</th>
                    <th>Телефон</th>
                    <th>Дата создания</th>
                </tr>
                </thead>
                <tbody>
                <?
                if(mycount($this->row) > 0){
                    foreach ($this->row as $key => $value){?>
                        <tr>
                            <td class="text-right"><?=$value['work_id']?></td>
                            <td class="text-left"><a href="/work/work-edit/work_id/<?=$value['work_id']?>/"><?=$value['address']?></a></td>
                            <td class="text-left"><?=$value['client_type_text']?></td>
                            <td class="text-left"><?=$value['client_fio']?></td>
                            <td class="text-left"><?=$value['client_phone']?></td>
                            <td class="text-center"><?=$value['date_create']?></td>
                        </tr>
                        <?
                    }
                }
                ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $("#employee_search").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#employee_table tbody tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>