<div class="modal-body" id="modal_body">
    <form id="form_id">
        <input type="hidden" value="<?=$this->material_smeta_id?>" name="material_smeta_id">

        <div class="form-group">
            <label class="control-label " for="room_id">Значение </label>
            <input type="number" step="any" id="material_price" name="material_price" value="<?=$this->row['material_price']?>" placeholder="Значение" class="form-control" autocomplete="off" required>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-sm px-4 btn-outline-success mb-1" onclick="updSmetaPrice()">Сохранить</button>
    <button type="button" class="btn btn-sm px-4 btn-outline-danger mb-1" data-dismiss="modal">Закрыть</button>
</div>

<script>
    function updSmetaPrice(){
        main_loader_show();
        var send_data = new FormData($("#form_id")[0]);

        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/work/work-edit/mode/upd-smeta-price/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    $('.modal').modal('hide');
                    toastSucces('Успех');
                    $('#smeta_list').load('/work/work-smeta-list/work_id/<?=$this->work_id?>');
                }
                main_loader_hide();
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }

</script>