<?
$this->headTitle('Ремонт №'.$this->remont_id);
$this->placeholder('page-header')->set('Ремонт №'.$this->remont_id);
?>
<div class="row">
    <div class="col-12 col-md-12">
        <div class="alert bgc-blue-l1 text-dark-m2 border-0 text-110 mb-0 p-3">
            <div style="float:left; margin-right: 40px;">
                <p>ФИО: <?=$this->row['fio']?></p>
                <p>Адрес: <?=$this->row['address']?></p>
                <p>Телефон клиента: <?=$this->row['client_phone']?></p>
            </div>
            <div style="float:left; margin-right: 40px;">
                <p>Тип дома: <?=$this->row['house_type_text']?></p>
                <p>Площадь дома: <?=$this->row['area_house']?> кв.м</p>
                <p>Площадь участка: <?=$this->row['area_field']?>ст.</p>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
        <br>
        <div class="dcard">
            <ul class="nav nav-tabs bgc-secondary-l3 border-y-1 brc-secondary-l3" role="tablist">
                <li class="nav-item mr-2px">
                    <a id="home1-tab-btn" class="d-style active btn btn-tp btn-light-secondary btn-h-white btn-a-text-dark btn-a-white text-95 px-3 px-sm-4 py-25 radius-0 border-0" data-toggle="tab" href="#home1" role="tab" aria-controls="home1" aria-selected="true">
                        <span class="v-active position-tl w-100 border-t-3 brc-blue mt-n2px"></span>
                        Общее
                    </a>
                </li>
                <li class="nav-item">
                    <a id="more1-tab-btn" class="d-style btn btn-tp btn-light-secondary btn-h-white btn-a-text-dark btn-a-white text-95 px-3 px-sm-4 py-25 radius-0 border-0" data-toggle="tab" href="#stages" role="tab" aria-controls="more1" aria-selected="false">
                        <span class="v-active position-tl w-100 border-t-3 brc-blue mt-n2px"></span>
                        Этапы
                    </a>
                </li>
                <li class="nav-item mr-2px">
                    <a id="profile1-tab-btn" class="d-style btn btn-tp btn-light-secondary btn-h-white btn-a-text-dark btn-a-white text-95 px-3 px-sm-4 py-25 radius-0 border-0" data-toggle="tab" href="#rooms" role="tab" aria-controls="profile1" aria-selected="false">
                        <span class="v-active position-tl w-100 border-t-3 brc-blue mt-n2px"></span>
                        Комнаты
                    </a>
                </li>
                <li class="nav-item">
                    <a id="more1-tab-btn" class="d-style btn btn-tp btn-light-secondary btn-h-white btn-a-text-dark btn-a-white text-95 px-3 px-sm-4 py-25 radius-0 border-0" data-toggle="tab" href="#measures" role="tab" aria-controls="more1" aria-selected="false">
                        <span class="v-active position-tl w-100 border-t-3 brc-blue mt-n2px"></span>
                        Замеры
                    </a>
                </li>
                <li class="nav-item mr-2px">
                    <a id="profile1-tab-btn" class="d-style btn btn-tp btn-light-secondary btn-h-white btn-a-text-dark btn-a-white text-95 px-3 px-sm-4 py-25 radius-0 border-0" data-toggle="tab" href="#birefs" role="tab" aria-controls="profile1" aria-selected="false">
                        <span class="v-active position-tl w-100 border-t-3 brc-blue mt-n2px"></span>
                        Бриф
                    </a>
                </li>
                <li class="nav-item mr-2px">
                    <a id="profile1-tab-btn" class="d-style btn btn-tp btn-light-secondary btn-h-white btn-a-text-dark btn-a-white text-95 px-3 px-sm-4 py-25 radius-0 border-0" data-toggle="tab" href="#materials" role="tab" aria-controls="profile1" aria-selected="false">
                        <span class="v-active position-tl w-100 border-t-3 brc-blue mt-n2px"></span>
                        Материалы
                    </a>
                </li>
                <li class="nav-item">
                    <a id="more1-tab-btn" class="d-style btn btn-tp btn-light-secondary btn-h-white btn-a-text-dark btn-a-white text-95 px-3 px-sm-4 py-25 radius-0 border-0" data-toggle="tab" href="#projects" role="tab" aria-controls="more1" aria-selected="false">
                        <span class="v-active position-tl w-100 border-t-3 brc-blue mt-n2px"></span>
                        Проекты ремонта
                    </a>
                </li>
            </ul>

            <div class="tab-content bgc-white p-35 border-0">
                <div class="tab-pane fade show active text-95" id="home1" role="tabpanel" aria-labelledby="home1-tab-btn">
                    <div class="row">
                        <div class="col-lg-5 col-md-5 col-sm-5">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <form id="form_remont">
                                    <input type="hidden" name="remont_id" value="<?=$this->remont_id?>">
                                    <div class="form-group pull-left margin-right-10">
                                        <label class="control-label no-padding-right" for="remont_start_date">Дата старта ремонта</label>
                                        <p style="font-size: 15px;"><?=$this->row['remont_start_date'] ?? 'Нет данных'?></p>
                                    </div>
                                    <div class="form-group pull-left margin-right-10">
                                        <label class="control-label no-padding-right" for="measure_date">Дата замера</label>
                                        <p style="font-size: 15px;"><?=$this->row['measure_date'] ?? 'Нет данных'?></p>
                                    </div>
                                    <div class="clearfix"></div>
                                    <div class="form-group pull-left margin-right-10">
                                        <label class="control-label no-padding-right">Замерщик</label>
                                        <p style="font-size: 15px;"><?=$this->row['measure_name'] ?? 'Нет данных'?></p>
                                    </div>
                                    <div class="clearfix"></div>
                                    <div class="form-group pull-left margin-right-10">
                                        <label class="control-label no-padding-right">Дизайнер</label>
                                        <p style="font-size: 15px;"><?=$this->row['designer_name'] ?? 'Нет данных'?></p>
                                    </div>
                                    <div class="clearfix"></div>
                                    <div class="form-group pull-left margin-right-10">
                                        <label class="control-label no-padding-right">Технолог</label>
                                        <p style="font-size: 15px;"><?=$this->row['tech_name'] ?? 'Нет данных'?></p>
                                    </div>
                                    <div class="clearfix"></div>
                                    <div class="form-group pull-left margin-right-10">
                                        <label class="control-label no-padding-right">Подрядчик</label>
                                        <p style="font-size: 15px;"><?=$this->row['contractor_name'] ?? 'Нет данных'?></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </form>
                            </div>
                        </div>
                        <div id="mark_list">
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>

                <div class="tab-pane fade text-95" id="stages" role="tabpanel" aria-labelledby="more1-tab-btn">
                    <a href="javascript:void(0)" onclick="showStageForm(<?=$this->remont_id?>, 0)" class="btn btn-info btn-xs pull-right">Добавить</a>
                    <div class="clearfix"></div>
                    <hr>
                    <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Этап</th>
                            <th>Статус</th>
                            <th>Комментарий</th>
                            <th>Работник</th>
                            <th>Дата создания</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?
                        if(mycount($this->row_stage) > 0){
                            $i = 0;
                            $background = '';
                            foreach ($this->row_stage as $key => $value){
                                $i++;
                                $background = '';
                                if($value['stage_status_code'] == 'stage_check'){
                                    $background = '#b3e0fc';
                                }elseif ($value['stage_status_code'] == 'stage_check_fail'){
                                    $background = '#fcb3b3';
                                }elseif ($value['stage_status_code'] == 'fail_check'){
                                    $background = '#f7fcb3';
                                }elseif ($value['stage_status_code'] == 'done'){
                                    $background = '#befcb3';
                                }
                                ?>
                                <tr style="background-color: <?=$background?>">
                                    <td class="text-right"><?=$i?></td>
                                    <td class="text-left"><?=$value['stage_name']?></td>
                                    <td class="text-left"><?=$value['stage_status_name']?></td>
                                    <td class="text-left"><?=$value['stage_comment']?></td>
                                    <td class="text-left"><?=$value['fio']?></td>
                                    <td class="text-center"><?=$value['date_create']?></td>
                                    <td class="text-center">
                                        <div class="action-buttons">
                                            <a class="btn btn-xs btn-danger" href="javascript:void(0);" onclick="delRemontStage(<?=$value['remont_stage_id']?>, this)">
                                                <i class="fa fa-trash" aria-hidden="true">
                                                </i>  Удалить
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <?
                            }
                        }
                        ?>
                        </tbody>
                    </table>
                </div>

                <div class="tab-pane fade text-95" id="rooms" role="tabpanel" aria-labelledby="more1-tab-btn">
                    <a href="javascript:void(0)" onclick="showRoomForm(<?=$this->remont_id?>, 0)" class="btn btn-info btn-xs pull-right">Добавить</a>
                    <div class="clearfix"></div>
                    <hr>
                    <div id="room_list">

                    </div>
                </div>

                <div class="tab-pane fade text-95" id="measures" role="tabpanel" aria-labelledby="more1-tab-btn">
                    <h5>Замеры(Документы)  <a href="javascript:void(0)" onclick="showMeasureDocForm(<?=$this->remont_id?>, 0)" class="btn btn-info btn-xs pull-right">Добавить</a>
                    </h5>
                    <div id="measure_doc">

                    </div>
                    <hr>
                    <div id="room_measure_list">

                    </div>
                </div>

                <div class="tab-pane fade text-95" id="birefs" role="tabpanel" aria-labelledby="profile1-tab-btn">
                    <div id="room_brief_list">

                    </div>
                </div>

                <div class="tab-pane fade text-95" id="materials" role="tabpanel" aria-labelledby="profile1-tab-btn">
                    <div id="room_material_list">

                    </div>
                </div>

                <div class="tab-pane fade text-95" id="projects" role="tabpanel" aria-labelledby="more1-tab-btn">
                    <a href="javascript:void(0)" onclick="showProjectForm(<?=$this->remont_id?>, 0)" class="btn btn-info btn-xs pull-right">Добавить</a>
                    <div class="clearfix"></div>
                    <hr>
                    <div id="project_list">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $( document ).ready(function() {
        $('#room_list').load('/remont/remont-room-list/remont_id/<?=$this->remont_id?>');
        $('#room_brief_list').load('/remont/remont-room-brief/remont_id/<?=$this->remont_id?>');
        $('#room_material_list').load('/remont/remont-room-material/remont_id/<?=$this->remont_id?>');
        $('#room_measure_list').load('/remont/remont-room-measure/remont_id/<?=$this->remont_id?>');
        $('#project_list').load('/remont/remont-project-list/remont_id/<?=$this->remont_id?>');
        $('#measure_doc').load('/remont/remont-measure-doc/remont_id/<?=$this->remont_id?>');
        $('#material_type_id').on('change', function() {
            material_type_id = this.value;
            loadMaterialSelect(material_type_id);
        });
        $('#material_id').on('change', function() {
            material_id = this.value;
            loadMaterialPrice(material_id);
        });
        loadMarkList();
    });
    function loadMaterialSelect(material_type_id) {
        main_loader_show();
        $.ajax({
            type: 'POST',
            url: "/remont/material-select-form/material_type_id/"+ material_type_id +"/",
            success: function(data){
                $('#material').html(data);
                main_loader_hide();
            }
        });
    }
    function loadMarkList() {
        main_loader_show();
        $.ajax({
            type: 'POST',
            url: "/remont/remont-mark-list/remont_id/"+ <?=$this->remont_id?> +"/",
            success: function(data){
                $('#mark_list').html(data);
                main_loader_hide();
            }
        });
    }
    function loadMaterialPrice(material_id) {
        main_loader_show();
        $.ajax({
            type: 'POST',
            url: "/remont/remont-edit/mode/get-price/material_id/"+ material_id +"/",
            success: function(data){
                $("#material_price").val(data.result['value']);
                main_loader_hide();
            }
        });
    }
    function upd_remont(){
        var fd = new FormData($("#form_remont")[0]);
        $.ajax({
            type: 'POST',
            url: "/remont/remont-edit/mode/upd/",
            data: fd,
            success: function(data){
                if(data.result['status'] == false){
                    alert(data.result['error']);
                    toastError('Ошибка при редактировании');
                } else{
                    toastSucces('Ремонт отредактирован');
                    window.location.reload();
                }
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }

    function showRoomForm(remont_id, remont_room_id){
        $('#modal-container').find('.modal-dialog').addClass('modal-md');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        $('#modal-header-container').append('Добавить комнату');
        $.ajax({
            type: 'POST',
            url: "/remont/remont-room-edit/",
            data: {"remont_id" : remont_id,
                   "remont_room_id" : remont_room_id},
            async: true,
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $("#modal-container").filter('.modal').modal();
    }

    function showStageForm(remont_id){
        $('#modal-container').find('.modal-dialog').addClass('modal-md');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        $('#modal-header-container').append('Добавить этап');
        $.ajax({
            type: 'POST',
            url: "/remont/remont-stage-form/",
            data: {"remont_id" : remont_id},
            async: true,
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $("#modal-container").filter('.modal').modal();
    }

    function showProjectForm(remont_id, remont_project_id){
        $('#modal-container').find('.modal-dialog').addClass('modal-md');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        $('#modal-header-container').append('Добавить проект');
        $.ajax({
            type: 'POST',
            url: "/remont/remont-project-edit/",
            data: {"remont_id" : remont_id,
                   "remont_project_id" : remont_project_id},
            async: true,
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $("#modal-container").filter('.modal').modal();
    }
    function showMeasureDocForm(remont_id, remont_measure_doc_id){
        $('#modal-container').find('.modal-dialog').addClass('modal-md');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        $('#modal-header-container').append('Добавить вложение');
        $.ajax({
            type: 'POST',
            url: "/remont/remont-measure-doc-edit/",
            data: {"remont_id" : remont_id,
                   "remont_measure_doc_id" : remont_measure_doc_id},
            async: true,
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $("#modal-container").filter('.modal').modal();
    }

    function delRemontRoom(remont_room_id, ob){
        if (!confirm("Вы действительно хотите удалить комнату ?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/remont/remont-edit/mode/del-room/remont_room_id/" + remont_room_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Комната удалена');
                    $(ob).closest("tr").remove();
                }
            }
        });
    }

    function delRemontStage(remont_stage_id, ob){
        if (!confirm("Вы действительно хотите удалить этап?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/remont/remont-edit/mode/del-stage/remont_stage_id/" + remont_stage_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Этап удален');
                    $(ob).closest("tr").remove();
                }
            }
        });
    }

    function delRemontProject(remont_project, ob){
        if (!confirm("Вы действительно хотите удалить проект ремонта?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/remont/remont-edit/mode/del-project/remont_project_id/" + remont_project_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Проект ремонта удален');
                    $(ob).closest("tr").remove();
                }
            }
        });
    }
    function delMeasureDoc(remont_measure_doc_id, ob){
        if (!confirm("Вы действительно хотите удалить вложение?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/remont/remont-edit/mode/del-measure-doc/remont_measure_doc_id/" + remont_measure_doc_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Вложение удалено');
                    $(ob).closest("tr").remove();
                }
            }
        });
    }
    function acceptProject(remont_project_id, is_accepted){
        if (!confirm("Вы действительно хотите утвердить проект ремонта?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/remont/remont-edit/mode/accept-project/remont_project_id/" + remont_project_id + "/is_accepted/" + is_accepted + "/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Проект ремонта утвержден');
                    $('#project_list').load('/remont/remont-project-list/remont_id/<?=$this->remont_id?>');
                }
            }
        });
    }

</script>