<!-- this footer is shown in device width above `sm` -->
<footer class="footer footer-fixed">
    <div class="footer-inner">
        <div class="h-100 pt-3 border-t-1 brc-secondary-l2 bgc-white-tp1 shadow">
            <span class="text-primary-m1 font-bolder text-120"></span>
            <span class="text-secondary-d2">Application &copy; <?=date('Y')?></span>
        </div>
    </div><!-- .footer-inner -->
</footer>
<!-- scroll to top button -->
<div class="footer-tools mb-5 mb-sm-0 footer-fixed">
    <a href="#" class="btn-scroll-up btn btn-white brc-black-tp6 px-25 py-2 text-95 border-2 radius-round mb-25 mr-2">
        <i class="fa fa-angle-double-up w-2 h-2"></i>
    </a>
</div>