<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <base href="../"/>

    <? echo $this->headTitle('')->setSeparator(' - ')->setAutoEscape(false) ?>
    <!-- include common vendor stylesheets & fontawesome -->
    <link rel="stylesheet" type="text/css"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css"
          href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/fontawesome.min.css">
    <link rel="stylesheet" type="text/css"
          href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/regular.min.css">
    <link rel="stylesheet" type="text/css"
          href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/brands.min.css">
    <link rel="stylesheet" type="text/css"
          href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/solid.min.css">

    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/chosen-js@1.8.7/chosen.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/color-themes-for-google-code-prettify@2.0.4/dist/themes/atelier-sulphurpool-light.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.18/dist/css/bootstrap-select.min.css">

    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/free-jqgrid@4.15.5/css/ui.jqgrid.min.css">

    <!-- include vendor stylesheets used in "Dashboard 2" page. see "/views//pages/partials/dashboard-2/@vendor-stylesheets.hbs" -->
    <!-- include fonts -->
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600&display=swap">
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700&amp;display=swap">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.0/themes/smoothness/jquery-ui.css">
    <style>body.font-montserrat {
            font-family: 'Montserrat';
        }</style>
    <!-- ace.css -->
    <link rel="stylesheet" type="text/css" href="/dist/css/ace.min.css">
    <link rel="stylesheet" type="text/css" href="/dist/css/ace-themes.min.css">
    <link rel="stylesheet" type="text/css" href="/dist/css/style.css?v=1">
    <!-- favicon -->
    <link rel="icon" type="image/png" href="/assets/favicon.ico"/>
    <style>
        .sidebar-dark .nav > .nav-item > .nav-link {
            font-size: 0.88rem !important;
        }

        .loader-smr {
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
            -webkit-box-align: center;
            -ms-flex-align: center;
            align-items: center;
            -webkit-box-pack: center;
            -ms-flex-pack: center;
            justify-content: center;
            width: 40px;
            height: 40px;
            background-color: #fff;
            border-radius: 5px;
            -webkit-box-shadow: 0 3px 4px 0 rgba(0, 0, 0, .13);
            box-shadow: 0 3px 4px 0 rgba(0, 0, 0, .13);
            margin: 0;
        }

        .request-loader-smr {
            position: fixed;
            top: -45px;
            left: calc(50% - 20px);
            z-index: 1070;
            -webkit-transition: top .3s;
            -o-transition: top .3s;
            transition: top .3s;
        }

        .loader-smr__circle {
            -webkit-animation: rotating 1s linear infinite;
        }

        @-webkit-keyframes rotating {
            0% {
                -webkit-transform: rotate(0deg)
            }
            to {
                -webkit-transform: rotate(1turn)
            }
        }
        .selected-td{
            background-color: #cbe8f6 !important;
        }
        .with-lb{
            margin-top: 30px !important;
        }
        .rd-color{
            color: #00c6ff !important;
        }
        .nav-text span{
            width: 160px;
            word-break: break-word;
        }
        .chosen-select:invalid {
            height: 0px !important;
            opacity: 0 !important;
            position: absolute !important;
            display: flex !important;
            margin-top: 22px;
        }
        .ui-autocomplete {
            max-height: 300px;
            overflow-y: auto;
            /* prevent horizontal scrollbar */
            overflow-x: hidden;
        }
        /* IE 6 doesn't support max-height
         * we use height instead, but this forces the menu to always be this tall
         */
        * html .ui-autocomplete {
            height: 100px;
        }
    </style>

    <?php echo $this->headLink() ?>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <script>
        function imgErrorHref(image) {
            image.onerror = "";
            image.src = "/assets/nophoto.png";
            image.setAttribute('data-src', '/assets/nophoto.png');
            return false;
        }
    </script>
</head>