<div class="modal-body" id="modal_body">
    <form id="form_id">
        <div class="form-group">
            <label class="control-label " for="client_fio">ФИО</label>
            <input type="text" id="client_fio" placeholder="ФИО" class="form-control" name="client_fio">
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="phone_num">ФИО</label>
            <input type="text" id="phone" placeholder="Телефон" class="form-control" name="phone_num">
            <div class="clearfix"></div>
        </div>

        <div class="form-group">
            <label class="control-label " for="package_id">Пакет ремонта</label>
            <select class="form-control" id="platform" name="package_id">
                <option value="0">Выберите тип</option>
                <?foreach ($this->row as $value){?>
                    <option value="<?=$value['package_id']?>" <?if($this->package_id == $value['package_id']){?>selected<?}?>><?=$value['package_name']?></option>
                    <?
                }?>
            </select>
            <div class="clearfix"></div>
        </div>

        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-sm px-4 btn-outline-success mb-1" onclick="updRequest()">Сохранить</button>
    <button type="button" class="btn btn-sm px-4 btn-outline-danger mb-1" data-dismiss="modal">Закрыть</button>
</div>

<script>
    $(document).ready(function() {
        $("#phone").inputmask("+7(999) 999-9999");
    });
    function updRequest(){
        main_loader_show();
        var send_data = new FormData($("#form_id")[0]);

        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/index/index/mode/upd/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    $('.modal').modal('hide');
                    toastSucces('Заявка создана. Скоро с Вами свяжется наш менеджер.');
                }
                main_loader_hide();
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }
</script>