<label class="control-label " for="room_id">Материал</label>
<select class="form-control chosen-select" id="material_id" name="material_id" required>
    <option value="0">Выберите материал</option>
    <?foreach ($this->row as $value2){?>
        <option value="<?=$value2['material_id']?>"><?=$value2['material_name']?></option>
        <?
    }?>
</select>
<div class="clearfix"></div>

<script>
    $(document).ready(function() {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });

        $('#material_id').on('change', function() {
            material_id = this.value;
            loadMaterialPrice(material_id);
        });
    });
</script>