<div class="modal-body" id="modal_body">
    <form id="form_id">
        <input type="hidden" value="<?=$this->client_request_id?>" name="client_request_id">

        <div class="form-group">
            <label class="control-label " for="payment_type_id">Тип документа</label>
            <select class="form-control" id="platform" name="payment_type_id">
                <option value="0">Выберите тип</option>
                <?foreach ($this->row_type as $value){?>
                    <option value="<?=$value['payment_type_id']?>"><?=$value['payment_type_name']?></option>
                    <?
                }?>
            </select>
            <div class="clearfix"></div>
        </div>

        <div class="form-group">
            <label class="control-label " for="payment_sum">Сумма</label>
            <input type="number" step="any" id="payment_sum" placeholder="Сумма" class="form-control" value="<?=$this->row['payment_sum'] ?? null?>" name="payment_sum">
            <div class="clearfix"></div>
        </div>

        <div class="form-group">
            <label class="control-label " for="discount_percent">Файл</label>
            <div class="form-control no-padding">
                <input type="file" name="upload" id="upload" >
            </div>
            <div class="clearfix"></div>
        </div>

        <div class="form-group">
            <label class="control-label " for="payment_comment">Комментарий</label>
            <textarea class="form-control" name="payment_comment" style="height: 100px; overflow: hidden; overflow-wrap: break-word; resize: horizontal;" id="payment_comment" placeholder="Комментарии"><?=$this->row['payment_comment'] ?? null?></textarea>
            <div class="clearfix"></div>
        </div>

        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-sm px-4 btn-outline-success mb-1" onclick="updPayment()">Сохранить</button>
    <button type="button" class="btn btn-sm px-4 btn-outline-danger mb-1" data-dismiss="modal">Закрыть</button>
</div>

<script>
    $(document).ready(function() {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });
    });

    function updPayment(){
        main_loader_show();
        var send_data = new FormData($("#form_id")[0]);

        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/remont/client-request-edit/mode/upd-payment/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    $('.modal').modal('hide');
                    toastSucces('Успех');
                    $('#payments').load('/remont/payment-list/client_request_id/<?=$this->client_request_id?>');
                }
                main_loader_hide();
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }
</script>