<div class="modal-body" id="modal_body">
    <form id="form_id">
        <input type="hidden" value="<?=$this->remont_room_id?>" name="remont_room_id">
        <input type="hidden" value="<?=$this->remont_room_measure_id?>" name="remont_room_measure_id">

        <div class="form-group">
            <label class="control-label " for="room_id">Тип </label>
            <select class="form-control chosen-select" id="measure_type_id" name="measure_type_id">
                <option value="0">Выберите тип</option>
                <?foreach ($this->row_measure as $value){?>
                    <option value="<?=$value['measure_type_id']?>" <?if($value['measure_type_id'] == $this->row['measure_type_id']){?>selected<?}?>><?=$value['measure_type_name']?></option>
                    <?
                }?>
            </select>
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="room_id">Значение </label>
            <input type="number" step="any" id="measure_value" name="measure_value" value="<?=$this->row['measure_value']?>" placeholder="Значение" class="form-control" autocomplete="off" required>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-sm px-4 btn-outline-success mb-1" onclick="updRemontRoomMeasureModal()">Сохранить</button>
    <button type="button" class="btn btn-sm px-4 btn-outline-danger mb-1" data-dismiss="modal">Закрыть</button>
</div>

<script>
    $(document).ready(function() {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });


    });

    function updRemontRoomMeasureModal(){
        main_loader_show();
        var send_data = new FormData($("#form_id")[0]);

        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/remont/remont-edit/mode/upd-room-measure/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    $('.modal').modal('hide');
                    toastSucces('Успех');
                    loadTableMeasure(<?=$this->remont_room_id?>);
                }
                main_loader_hide();
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }

</script>