<div class="table-responsive">
    <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
        <thead>
        <tr>
            <th>ID</th>
            <th>Название</th>
            <th>Тип комнаты</th>
            <th>Дата создания</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?
        if(mycount($this->row) > 0){
            $i = 1;
            foreach ($this->row as $key => $value){
                ?>
                <tr>
                    <td class="text-right"><?=$i?></td>
                    <td class="text-left"><?=$value['remont_room_name']?></td>
                    <td class="text-left"><?=$value['room_name']?></td>
                    <td class="text-center"><?=$value['date_create']?></td>
                    <td class="text-center">
                        <div class="action-buttons">
                            <a class="btn btn-xs btn-danger" href="javascript:void(0);" onclick="delRemontRoom(<?=$value['remont_room_id']?>, this)">
                                <i class="fa fa-trash" aria-hidden="true">
                                </i>  Удалить
                            </a>
                            <a class="btn btn-xs btn-primary" href="javascript:void(0);" onclick="showRoomForm(<?=$value['remont_id']?>, <?=$value['remont_room_id']?>)">
                                <i class="fa fa-edit" aria-hidden="true">
                                </i>  Изменить
                            </a>
                        </div>
                    </td>
                </tr>
                <?
                $i = $i + 1;
            }
        }
        ?>
        </tbody>
    </table>
</div>