<div class="modal-body" id="modal_body">
    <form id="form_id">
        <input type="hidden" value="<?=$this->remont_id?>" name="remont_id">
        <input type="hidden" value="<?=$this->remont_measure_doc_id?>" name="remont_measure_doc_id">

        <div class="form-group">
            <label class="control-label " for="doc_name">Наименование</label>
            <input type="text" id="doc_name" placeholder="Наименование" class="form-control" value="<?=$this->row['doc_name'] ?? null?>" name="doc_name">
            <div class="clearfix"></div>
        </div>

        <div class="form-group">
            <label class="control-label " for="discount_percent">Файл</label>
            <div class="form-control no-padding">
                <input type="file" name="upload" id="upload" >
            </div>
            <div class="clearfix"></div>
        </div>

        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-sm px-4 btn-outline-success mb-1" onclick="updMeasureDoc()">Сохранить</button>
    <button type="button" class="btn btn-sm px-4 btn-outline-danger mb-1" data-dismiss="modal">Закрыть</button>
</div>

<script>
    $(document).ready(function() {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });
    });

    function updMeasureDoc(){
        main_loader_show();
        var send_data = new FormData($("#form_id")[0]);

        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/remont/remont-edit/mode/upd-measure-doc/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    $('.modal').modal('hide');
                    toastSucces('Успех');
                    $('#measure_doc').load('/remont/remont-measure-doc/remont_id/<?=$this->remont_id?>');
                }
                main_loader_hide();
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }
</script>