<form id="form_id_smeta">
    <input type="hidden" value="<?=$this->remont_id?>" name="remont_id">
    <div class="row">
        <div class="box1 col-md-3">
            <label class="control-label " for="room_id">Тип материала</label>
            <select class="form-control" id="material_type_id" name="material_type_id" required>
                <option value="0">Выберите тип</option>
                <?foreach ($this->row_type as $value1){?>
                    <option value="<?=$value1['material_type_id']?>"><?=$value1['material_type_name']?></option>
                    <?
                }?>
            </select>
            <div class="clearfix"></div>
        </div>
        <div class="box1 col-md-3" id="material">
        </div>
    </div>
    <div class="row">
        <div class="box1 col-md-3">
            <label class="control-label " for="material_price">Цена</label>
            <input type="number" step="any" id="material_price" name="material_price" placeholder="Цена" class="form-control" autocomplete="off" required>
            <div class="clearfix"></div>
        </div>
        <div class="box1 col-md-3">
            <label class="control-label " for="material_cnt">Кол-во</label>
            <input type="number" step="any" id="material_cnt" name="material_cnt" placeholder="Кол-во" class="form-control" autocomplete="off" required>
            <div class="clearfix"></div>
        </div>
        <div class="box1 col-md-3">
            <button type="button" class="btn btn-sm px-4 btn-success mb-1" style="margin-top: 25px;" onclick="updSmetaMaterial()">Сохранить</button>
        </div>
    </div>
    <div class="clearfix"></div>
</form>
<div class="clearfix"></div>
<hr>
<div class="table-responsive">
    <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
        <thead>
        <tr>
            <th>ID</th>
            <th>Материал</th>
            <th>Тип материала</th>
            <th>Кол-во</th>
            <th>Цена</th>
            <th>Сумма</th>
            <th>Дата создания</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?
        if(mycount($this->row) > 0){
            $i = 1;
            $sum = 0;
            foreach ($this->row as $key => $value){
                $sum = $sum + $value['material_sum'];
                ?>
                <tr>
                    <td class="text-right"><?=$i?></td>
                    <td class="text-left"><?=$value['material_name']?></td>
                    <td class="text-left"><?=$value['material_type_name']?></td>
                    <td class="text-right"><?=tenge_text($value['material_cnt'])?> <?=$value['unit_type_name']?></td>
                    <td class="text-right"><?=tenge_text($value['material_price'])?> тг</td>
                    <td class="text-right" style="border-right: 3px solid #f1cc0b; border-left: 3px solid #f1cc0b;"><?=tenge_text($value['material_sum'])?> тг</td>
                    <td class="text-center"><?=$value['date_create']?></td>
                    <td class="text-center">
                        <div class="action-buttons">
                            <a class="btn btn-xs btn-danger" href="javascript:void(0);" onclick="delSmetaMaterial(<?=$value['material_smeta_id']?>, this)">
                                <i class="fa fa-trash" aria-hidden="true">
                                </i>  Удалить
                            </a>
                        </div>
                    </td>
                </tr>
                <?
                $i = $i + 1;
            }?>
                <tr>
                    <td class="text-right font-bold" colspan="5">Общая сумма</td>
                    <td class="text-right font-bold"><?=tenge_text($sum)?> тг</td>
                    <td class="text-right" colspan="2"></td>
                </tr>
            <?
        }
        ?>
        </tbody>
    </table>
</div>
<script>
    $(document).ready(function() {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });

        $('#material_type_id').on('change', function() {
            material_type_id = this.value;
            loadMaterialSelect(material_type_id);
        });
        $('#material_id').on('change', function() {
            material_id = this.value;
            loadMaterialPrice(material_id);
        });
    });
    function loadMaterialSelect(material_type_id) {
        main_loader_show();
        $.ajax({
            type: 'POST',
            url: "/remont/material-select-form/material_type_id/"+ material_type_id +"/",
            success: function(data){
                $('#material').html(data);
                main_loader_hide();
            }
        });
    }
    function loadMaterialPrice(material_id) {
        main_loader_show();
        $.ajax({
            type: 'POST',
            url: "/remont/remont-edit/mode/get-price/material_id/"+ material_id +"/",
            success: function(data){
                $("#material_price").val(data.result['value']);
                main_loader_hide();
            }
        });
    }

    function updSmetaMaterial(){
        main_loader_show();
        var send_data = new FormData($("#form_id_smeta")[0]);

        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/remont/remont-edit/mode/upd-smeta/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    $('.modal').modal('hide');
                    toastSucces('Успех');
                    $('#smeta_list').load('/remont/remont-smeta-list/remont_id/<?=$this->remont_id?>');
                }
                main_loader_hide();
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }

    function delSmetaMaterial(material_smeta_id, ob){
        if (!confirm("Вы действительно хотите удалить материал из сметы?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/remont/remont-edit/mode/del-smeta/material_smeta_id/" + material_smeta_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Материал удален');
                    $(ob).closest("tr").remove();
                }
            }
        });
    }
</script>