<div class="dcard">
    <ul class="nav nav-tabs bgc-secondary-l3 border-y-1 brc-secondary-l3" role="tablist">
        <?foreach ($this->row as $value){?>
            <li class="nav-item mr-2px">
                <a id="home1-tab-btn" class="d-style btn btn-tp btn-light-secondary btn-h-white btn-a-text-dark btn-a-white text-95 px-3 px-sm-4 py-25 radius-0 border-0" onclick="loadTableMaterial(<?=$value['remont_room_id']?>)" data-toggle="tab" href="#<?=$value['room_code']?>_<?=$value['remont_room_id']?>_material" role="tab" aria-controls="home1" aria-selected="true">
                    <span class="v-active position-tl w-100 border-t-3 brc-blue mt-n2px"></span>
                    <?=$value['remont_room_name']?>
                </a>
            </li>
            <?
        }?>
    </ul>

    <div class="tab-content bgc-white p-35 border-0">
        <?foreach ($this->row as $value){?>
            <div class="tab-pane fade show text-95" id="<?=$value['room_code']?>_<?=$value['remont_room_id']?>_material" role="tabpanel" aria-labelledby="home1-tab-btn">
                <form id="form_id_material_<?=$value['remont_room_id']?>">
                    <input type="hidden" value="<?=$value['remont_room_id']?>" name="remont_room_id">
                    <input type="hidden" value="0" name="remont_material_id">
                    <div class="row">
                        <div class="box1 col-md-3">
                            <label class="control-label " for="room_id">Тип материала</label>
                            <select class="form-control" onchange="loadMaterial(this, <?=$value['remont_room_id']?>)" id="material_type_id" name="material_type_id" required>
                                <option value="0">Выберите тип</option>
                                <?foreach ($this->row_material_type as $value1){?>
                                    <option value="<?=$value1['material_type_id']?>"><?=$value1 ['material_type_name']?></option>
                                    <?
                                }?>
                            </select>
                            <div class="clearfix"></div>
                        </div>
                        <div class="box1 col-md-3" style="display:none;" id="material_select_<?=$value['remont_room_id']?>">
                        </div>
                        <div class="box1 col-md-3">
                            <label class="control-label " for="material_cnt">Кол-во</label>
                            <input type="number" step="any" id="material_cnt" name="material_cnt" placeholder="Кол-во" class="form-control" autocomplete="off" required>
                            <div class="clearfix"></div>
                        </div>
                        <div class="box1 col-md-3">
                            <button type="button" class="btn btn-sm px-4 btn-success mb-1" style="margin-top: 25px;" onclick="updRemontRoomMaterial(<?=$value['remont_room_id']?>)">Сохранить</button>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </form>
                <div class="clearfix"></div>
                <hr>
                <div id="room_material_<?=$value['remont_room_id']?>">

                </div>
            </div>
            <?
        }?>
    </div>
</div>
<script>
    function loadMaterial(ob, remont_room_id) {
        main_loader_show();

        material_type_id = ob.value;

        $.ajax({
            type: 'POST',
            url: "/remont/material-select-form/material_type_id/"+ material_type_id +"/",
            success: function(data){
                $('#material_select_'+remont_room_id).html(data);
                $('#material_select_'+remont_room_id).show();
                main_loader_hide();
            }
        });
    }
    function loadTableMaterial(remont_room_id) {
        $('#room_material_'+remont_room_id).load('/remont/remont-material-table/remont_room_id/'+remont_room_id);
    }
    function showMaterialForm(remont_room_id, remont_material_id){
        $('#modal-container').find('.modal-dialog').addClass('modal-md');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        $('#modal-header-container').append('Добавить материал');
        $.ajax({
            type: 'POST',
            url: "/remont/remont-room-material-edit/",
            data: {"remont_room_id" : remont_room_id, "remont_material_id" : remont_material_id},
            async: true,
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $("#modal-container").filter('.modal').modal();
    }
    function delRemontRoomMaterial(remont_material_id, ob){
        if (!confirm("Вы действительно хотите удалить выбор клиента?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/remont/remont-edit/mode/del-room-material/remont_material_id/" + remont_material_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Выбор удален');
                    $(ob).closest("tr").remove();
                }
            }
        });
    }

    function updRemontRoomMaterial(remont_room_id){
        main_loader_show();
        var send_data = new FormData($("#form_id_material_"+remont_room_id)[0]);

        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/remont/remont-edit/mode/upd-room-material/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    $('.modal').modal('hide');
                    toastSucces('Успех');
                    loadTableMaterial(remont_room_id);
                }
                main_loader_hide();
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }

</script>