<div class="dcard">
    <ul class="nav nav-tabs bgc-secondary-l3 border-y-1 brc-secondary-l3" role="tablist">
        <?foreach ($this->row as $value){?>
            <li class="nav-item mr-2px">
                <a id="home1-tab-btn" class="d-style btn btn-tp btn-light-secondary btn-h-white btn-a-text-dark btn-a-white text-95 px-3 px-sm-4 py-25 radius-0 border-0" onclick="loadTableMeasure(<?=$value['remont_room_id']?>)" data-toggle="tab" href="#<?=$value['room_code']?>_<?=$value['remont_room_id']?>_measure" role="tab" aria-controls="home1" aria-selected="true">
                    <span class="v-active position-tl w-100 border-t-3 brc-blue mt-n2px"></span>
                    <?=$value['remont_room_name']?>
                </a>
            </li>
            <?
        }?>
    </ul>

    <div class="tab-content bgc-white p-35 border-0">
        <?foreach ($this->row as $value){?>
            <div class="tab-pane fade show text-95" id="<?=$value['room_code']?>_<?=$value['remont_room_id']?>_measure" role="tabpanel" aria-labelledby="home1-tab-btn">
                <form id="form_id_<?=$value['remont_room_id']?>">
                    <input type="hidden" value="<?=$value['remont_room_id']?>" name="remont_room_id">
                    <input type="hidden" value="0" name="remont_room_measure_id">
                    <div class="row">
                        <div class="box1 col-md-3">
                            <label class="control-label " for="room_id">Тип замера</label>
                            <select class="form-control chosen-select" id="measure_type_id" name="measure_type_id" required>
                                <option value="0">Выберите тип</option>
                                <?foreach ($this->row_measure as $value1){?>
                                    <option value="<?=$value1['measure_type_id']?>"><?=$value1 ['measure_type_name']?></option>
                                    <?
                                }?>
                            </select>
                            <div class="clearfix"></div>
                        </div>
                        <div class="box1 col-md-3">
                            <label class="control-label " for="measure_value">Значение замера</label>
                            <input type="number" step="any" id="measure_value" name="measure_value" placeholder="Значение" class="form-control" autocomplete="off" required>
                            <div class="clearfix"></div>
                        </div>
                        <div class="box1 col-md-3">
                            <button type="button" class="btn btn-sm px-4 btn-success mb-1" style="margin-top: 25px;" onclick="updRemontRoomMeasure(<?=$value['remont_room_id']?>)">Сохранить</button>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </form>
                <div class="clearfix"></div>
                <hr>
                <div id="room_measure_<?=$value['remont_room_id']?>">

                </div>
            </div>
            <?
        }?>
    </div>
</div>
<script>
    function loadTableMeasure(remont_room_id) {
        $('#room_measure_'+remont_room_id).load('/remont/remont-measure-table/remont_room_id/'+remont_room_id);
    }
    function showMeasureForm(remont_room_id, remont_room_measure_id){
        $('#modal-container').find('.modal-dialog').addClass('modal-md');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        $('#modal-header-container').append('Добавить выбор клиента');
        $.ajax({
            type: 'POST',
            url: "/remont/remont-room-measure-edit/",
            data: {"remont_room_id" : remont_room_id, "remont_room_measure_id" : remont_room_measure_id},
            async: true,
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $("#modal-container").filter('.modal').modal();
    }
    function delRemontRoomMeasure(remont_room_measure_id, ob){
        if (!confirm("Вы действительно хотите удалить выбор клиента?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/remont/remont-edit/mode/del-room-measure/remont_room_measure_id/" + remont_room_measure_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Выбор удален');
                    $(ob).closest("tr").remove();
                }
            }
        });
    }

    function updRemontRoomMeasure(remont_room_id){
        main_loader_show();
        var send_data = new FormData($("#form_id_"+remont_room_id)[0]);

        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/remont/remont-edit/mode/upd-room-measure/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    $('.modal').modal('hide');
                    toastSucces('Успех');
                    loadTableMeasure(remont_room_id);
                }
                main_loader_hide();
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }

</script>