<table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
    <thead>
    <tr>
        <th>ID</th>
        <th>Материал</th>
        <th>Тип</th>
        <th>Кол-во</th>
        <th>Дата создания</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?
    if(mycount($this->row) > 0){
        foreach ($this->row as $key => $value){?>
            <tr>
                <td class="text-right"><?=$value['remont_material_id']?></td>
                <td class="text-left"><?=$value['material_name']?></td>
                <td class="text-left"><?=$value['material_type_name']?></td>
                <td class="text-left"><?=$value['material_cnt']?> <?=$value['unit_type_name']?></td>
                <td class="text-center"><?=$value['date_create']?></td>
                <td class="text-center">
                    <div class="action-buttons">
                        <a class="btn btn-xs btn-danger" href="javascript:void(0);" onclick="delRemontRoomMaterial(<?=$value['remont_material_id']?>, this)">
                            <i class="fa fa-trash" aria-hidden="true">
                            </i>  Удалить
                        </a>
                    </div>
                </td>
            </tr>
            <?
        }
    }
    ?>
    </tbody>
</table>