
<div class="clearfix"></div>
<hr>
<div class="table-responsive">
    <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
        <thead>
        <tr>
            <th>ID</th>
            <th>Материал</th>
            <th>Тип материала</th>
            <th>Кол-во</th>
            <th>Цена</th>
            <th>Сумма</th>
            <th>Дата создания</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?
        if(mycount($this->row) > 0){
            $i = 1;
            $sum = 0;
            foreach ($this->row as $key => $value){
                $sum = $sum + $value['material_sum'];
                ?>
                <tr>
                    <td class="text-right"><?=$i?></td>
                    <td class="text-left"><?=$value['material_name']?></td>
                    <td class="text-left"><?=$value['material_type_name']?></td>
                    <td class="text-right"><?=tenge_text($value['material_cnt'])?> <?=$value['unit_type_name']?></td>
                    <td class="text-right"><?=tenge_text($value['material_price'])?> тг</td>
                    <td class="text-right" style="border-right: 3px solid #f1cc0b; border-left: 3px solid #f1cc0b;"><?=tenge_text($value['material_sum'])?> тг</td>
                    <td class="text-center"><?=$value['date_create']?></td>
                    <td class="text-center">
                        <div class="action-buttons">
                            <a class="btn btn-xs btn-primary" href="javascript:void(0);" onclick="showSmetaForm(<?=$this->remont_id?>, <?=$value['material_smeta_id']?>)">
                                <i class="fa fa-edit" aria-hidden="true">
                                </i>  Изменить
                            </a>
                            <a class="btn btn-xs btn-danger" href="javascript:void(0);" onclick="delSmetaMaterial(<?=$value['material_smeta_id']?>, this)">
                                <i class="fa fa-trash" aria-hidden="true">
                                </i>  Удалить
                            </a>
                        </div>
                    </td>
                </tr>
                <?
                $i = $i + 1;
            }?>
                <tr>
                    <td class="text-right font-bold" colspan="5">Общая сумма</td>
                    <td class="text-right font-bold"><?=tenge_text($sum)?> тг</td>
                    <td class="text-right" colspan="2"></td>
                </tr>
            <?
        }
        ?>
        </tbody>
    </table>
</div>
<script>
    $(document).ready(function() {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });


    });

    function showSmetaForm(remont_id, material_smeta_id){
        $('#modal-container').find('.modal-dialog').addClass('modal-md');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        $('#modal-header-container').append('Редактирование цены');
        $.ajax({
            type: 'POST',
            url: "/remont/remont-smeta-edit/",
            data: {"remont_id" : remont_id, "material_smeta_id" : material_smeta_id},
            async: true,
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $("#modal-container").filter('.modal').modal();
    }

    function updSmetaMaterial(){
        main_loader_show();
        var send_data = new FormData($("#form_id_smeta")[0]);

        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/remont/remont-edit/mode/upd-smeta/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    $('.modal').modal('hide');
                    toastSucces('Успех');
                    $('#smeta_list').load('/remont/remont-smeta-list/remont_id/<?=$this->remont_id?>');
                }
                main_loader_hide();
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }

    function delSmetaMaterial(material_smeta_id, ob){
        if (!confirm("Вы действительно хотите удалить материал из сметы?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/remont/remont-edit/mode/del-smeta/material_smeta_id/" + material_smeta_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Материал удален');
                    $(ob).closest("tr").remove();
                }
            }
        });
    }
</script>