<div class="modal-body" id="modal_body">
    <form id="form_id">
        <input type="hidden" value="<?=$this->banner_id?>" name="banner_id">

        <div class="form-group">
            <label class="control-label " for="banner_text">Текст</label>
            <input type="text" id="banner_text" placeholder="Текст" class="form-control" value="<?=$this->row['banner_text'] ?? null?>" name="banner_text">
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="order_num">Очередность</label>
            <input type="number" step="any" id="order_num" placeholder="Очередность" class="form-control" value="<?=$this->row['order_num'] ?? null?>" name="order_num">
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="is_active">Активный</label>
            <div>
                <select class="form-control" id="is_active" name="is_active" required>
                    <option value="0" <?=is_selected_html(0, $this->row['is_active'] ?? null)?>>Нет</option>
                    <option value="1" <?=is_selected_html(1, $this->row['is_active'] ?? null)?>>Да</option>
                </select>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="discount_percent">Фото</label>
            <div class="form-control no-padding">
                <input type="file" name="upload" id="upload" >
            </div>
            <div class="clearfix"></div>
        </div>

        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-sm px-4 btn-outline-success mb-1" onclick="updBanner()">Сохранить</button>
    <button type="button" class="btn btn-sm px-4 btn-outline-danger mb-1" data-dismiss="modal">Закрыть</button>
</div>

<script>
    $(document).ready(function() {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });
    });

    function updBanner(){
        main_loader_show();
        var send_data = new FormData($("#form_id")[0]);

        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/dict/banner-list/mode/upd/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    $('.modal').modal('hide');
                    toastSucces('Успех');
                    location.reload();
                }
                main_loader_hide();
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }
</script>