<div class="modal-body" id="modal_body">
    <form id="form_id">
        <input type="hidden" value="<?=$this->brief_type_id?>" name="brief_type_id">

        <div class="form-group">
            <label class="control-label " for="brief_type_name">Наименование</label>
            <input type="text" id="brief_type_name" placeholder="Наименование" class="form-control" value="<?=$this->row['brief_type_name'] ?? null?>" name="brief_type_name">
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="brief_type_code">Код</label>
            <input type="text" id="brief_type_code" placeholder="Код" class="form-control" value="<?=$this->row['brief_type_code'] ?? null?>" name="brief_type_code">
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="brief_type">Тип выборки</label>
            <div>
                <select class="form-control" id="brief_type" name="brief_type" required>
                    <option value="1" <?=is_selected_html(1, $this->row['brief_type'] ?? null)?>>Выборка</option>
                    <option value="2" <?=is_selected_html(2, $this->row['brief_type'] ?? null)?>>Свободное значение</option>
                </select>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-sm px-4 btn-outline-success mb-1" onclick="updBrief()">Сохранить</button>
    <button type="button" class="btn btn-sm px-4 btn-outline-danger mb-1" data-dismiss="modal">Закрыть</button>
</div>

<script>
    $(document).ready(function() {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });
    });

    function updBrief(){
        main_loader_show();
        var send_data = new FormData($("#form_id")[0]);

        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/dict/brief-type-list/mode/upd/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    $('.modal').modal('hide');
                    toastSucces('Успех');
                    location.reload();
                }
                main_loader_hide();
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }
</script>