<style>
    .modal-body .chosen-container {
        width: 100% !important;
    }
</style>
<div class="modal-body" id="modal_body">
    <form id="form_id">
        <input type="hidden" value="<?=$this->category_id?>" name="category_id">
        <input type="hidden" value="<?=$this->category_group_id?>" name="category_group_id">
        <div class="form-group">
            <label class="control-label " for="category_name">Название</label>
            <input type="text" id="category_name" placeholder="Название" class="form-control" value="<?=$this->row['category_name']?>" name="category_name">
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="category_code">Код</label>
            <input type="text" id="category_code" placeholder="Код" class="form-control" value="<?=$this->row['category_code']?>" name="category_code">
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="is_active">Активный</label>
            <div>
                <select class="form-control" id="is_active" name="is_active" required>
                    <option value="0" <?=is_selected_html(0, $this->row['is_active'] ?? null)?>>Нет</option>
                    <option value="1" <?=is_selected_html(1, $this->row['is_active'] ?? null)?>>Да</option>
                </select>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-sm px-4 btn-outline-success mb-1" onclick="categoryUpd()">Сохранить</button>
    <button type="button" class="btn btn-sm px-4 btn-outline-danger mb-1" data-dismiss="modal">Закрыть</button>
</div>
<script>
    $(document).ready(function() {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });
    });

    function categoryUpd(){
        var send_data = $('#form_id').serializeArray();
        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/dict/category-form/mode/upd/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Категория успешно обновлена');
                    showCategoryTable($('#category_group_id').val());
                    $(".modal").modal('hide');
                }
            }
        });
    }
</script>