<?
$this->headTitle('Подрядчики');
$this->placeholder('page-header')->set("Подрядчики");
?>

<style>
    .product-img{
        object-fit: contain;
        border: 1px solid #f2f2f2;
        width: 100px;
        height: 100px;
        padding: 3px;
    }
</style>
<div class="hr hr-10 dotted hr-double"></div>
<div class="row">
    <div class="col-lg-8 p-0" id="load">
        <div class="pos-rel ml-sm-auto order-last order-sm-0 float-left" style="margin-bottom: 5px;">
            <i class="fa fa-search position-lc ml-25 text-primary-m1"></i>
            <input type="text" class="form-control w-100 pl-45 radius-1 brc-primary-m4" id="sp_search" placeholder="Быстрый поиск ...">
        </div>
        <button type="button" name="add" class="btn btn-success float-left" style="margin-left: 5px;" onclick="showModal(0)" >
            <i class="ace-icon fa fa-plus bigger-125"></i>
            Добавить
        </button>
        <div class="clearfix"></div>

        <div class="card dcard mb-3" id="sp_table" draggable="false" style="">
            <div class="card-body p-0">
                <div class="p-3">
                    <div class="card-body p-0 table-responsive">
                        <table class="table mb-1">
                            <thead>
                            <tr class="text-primary-d3 text-95 text-center">
                                <th class="py-3 pl-35">ID</th>
                                <th class="text-center">Название</th>
                                <th class="text-center">Бин</th>
                                <th class="text-center">Адрес</th>
                                <th class="text-center">ФИО начальника</th>
                                <th class="text-center">Дата присоединения</th>
                                <th class="text-center">Активный</th>
                                <th class="text-center"></th>
                            </tr>
                            </thead>

                            <tbody>
                            <?
                            if(mycount($this->row) > 0){
                                foreach ($this->row as $key => $value){?>
                                    <tr class="bgc-h-orange-l4 text-600">
                                        <td class="text-right'"><?=$value['contractor_id']?></td>
                                        <td class="text-left"><?=$value['contractor_name']?></td>
                                        <td class="text-left"><?=$value['contractor_bin']?></td>
                                        <td class="text-left"><?=$value['contractor_address']?></td>
                                        <td class="text-left"><?=$value['contractor_cheif_fio']?></td>
                                        <td class="text-center"><?=$value['add_date']?></td>
                                        <td class="text-center">
                                            <input type="checkbox" id="is_active" class="ace-switch ace-switch-bars bgc-success-d2 ml-2" <?if($value['is_active'] == 1){?>checked<?}?> onchange="set_is_active(<?=$value['contractor_id']?>, this)">
                                        </td>
                                        <td class="pr-35 text-center" style="white-space: nowrap">
                                            <a href="javascript:void(0);" onclick="showModal(<?=$value['contractor_id']?>)" class="mx-2px btn radius-1 border-2 btn-xs btn-brc-tp btn-light-secondary btn-h-lighter-success btn-a-lighter-warning">
                                                <i class="fa fa-pencil-alt"></i>
                                            </a>
                                            <a href="javascript:void(0);" onclick="delContractor(<?=$value['contractor_id']?>,'<?=$value['contractor_name']?>', this)" class="mx-2px btn radius-1 border-2 btn-xs btn-brc-tp btn-light-secondary btn-h-lighter-danger btn-a-lighter-danger">
                                                <i class="fa fa-trash-alt"></i>
                                            </a>
                                        </td>
                                    </tr>
                                <?}
                            }?>
                            </tbody>
                        </table>
                    </div><!-- /.card-body -->
                </div>
            </div><!-- /.card-body -->
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('#modal').on('shown.bs.modal', function (e) {
            $(document).keypress(function(e) {
                var keycode = (e.keyCode ? e.keyCode : e.which);
                if (keycode == '13') {
                    updShop();
                }
            });
        });

        $("#sp_search").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#sp_table tbody tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });

    function set_is_active(contractor_id, ob) {
        var isChecked = $(ob).is(':checked');

        $.ajax({
            type: 'POST',
            url: "/dict/contractor-list/mode/set-active/",
            data:{contractor_id: contractor_id},
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                    $(ob).prop('checked', false);
                }else{
                    if(isChecked != false){
                        toastSucces('Подрядчик активный');
                    }else{
                        toastSucces('Подрядчик неактивный');
                    }
                }
            }
        });
    }

    function showModal(contractor_id){
        $('#modal-container').find('.modal-dialog').addClass('modal-md');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        $('#modal-header-container').append('Редактирование');
        $.ajax({
            type: 'POST',
            url: "/dict/contractor-edit/",
            data: {contractor_id : contractor_id},
            async: true,
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $(".modal").modal('show');
    }

    function delContractor(contractor_id, contractor_name, ob){
        if (!confirm("Вы действительно хотите удалить подрядчика " + contractor_name + " ?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/dict/contractor-list/mode/del/contractor_id/" + contractor_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Подрядчик ' + contractor_name + ' удален');
                    $(ob).closest("tr").remove();
                }
            }
        });
    }
</script>