<?
$this->headTitle('Детали запроса');
$this->placeholder('page-header')->set("Детали запроса");
?>
<style>
    .modal-body .chosen-container {
        width: 100% !important;
    }
</style>
<div class="row">
    <div class="col-lg-3" style="border-right: 1px solid #00a3d1">
        <form id="form_id">
            <input type="hidden" value="<?=$this->employee_request_id?>" name="employee_request_id">
            <div class="form-group">
                <label class="control-label " for="employee_request_type_id">Тип:</label>
                <h4><?=$this->row['employee_request_type_name']?></h4>
                <div class="clearfix"></div>
            </div>
            <div class="form-group">
                <label class="control-label " for="description">Описание:</label>
                <h4>
                    <?=$this->row['description']?>
                </h4>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
            <hr>
            <a href="/dict/employee-request-accept/" class="btn btn-sm px-4 btn-outline-danger mb-1">Закрыть</a>
        </form>
    </div>
    <div class="col-lg-9">
        <?if($this->employee_request_id <> 0){?>
            <h3>Вложения</h3>
            <div class="table-responsive">
                <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Документ</th>
                        <th>Дата создания</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?
                    if(mycount($this->row_doc) > 0){
                        $i = 1;
                        foreach ($this->row_doc as $key => $value){
                            ?>
                            <tr>
                                <td class="text-right"><?=$i?></td>
                                <td class="text-center"><?=$value['doc_name']?></td>
                                <td class="text-center"><?=$value['date_create']?></td>
                                <td class="text-center">
                                    <a class="btn btn-xs btn-success" href="<?=$value['doc_url']?>" target="_blank" download="<?=$value['doc_name']?>">
                                        <i class="fa fa-download" aria-hidden="true">
                                        </i>  Скачать
                                    </a>
                                </td>
                            </tr>
                            <?
                            $i = $i + 1;
                        }
                    }
                    ?>
                    </tbody>
                </table>
            </div>
            <h3>Список ответственных</h3>
            <div class="table-responsive">
                <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Ответственный</th>
                        <th>Сообщение</th>
                        <th>Статус</th>
                        <th>Ответ</th>
                        <th>

                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?
                    if(mycount($this->row_list) > 0){
                        $i = 1;
                        foreach ($this->row_list as $key => $value){
                            $status_name = '';
                            $color = '';
                            if($value['list_status'] == 2){
                                $status_name = 'Согласован';
                                $color = '#a7d5a7';
                            }elseif ($value['list_status'] == 3){
                                $status_name = 'Отказан';
                                $color = '#e99788';
                            }elseif ($value['list_status'] == 1){
                                $status_name = 'Переназначен';
                                $color = '#8899e9';
                            }
                            ?>
                            <tr>
                                <td class="text-right"><?=$i?></td>
                                <td class="text-left"><?=$value['list_fio']?></td>
                                <td class="text-left"><?=$value['request_text']?></td>
                                <td class="text-center">
                                    <span style="color: <?=$color?>"><?=$status_name?></span>
                                    <br>
                                    <?=$value['status_date']?>
                                </td>
                                <td class="text-left"><?=$value['status_comment']?></td>
                                <td class="text-center">
                                    <?if($this->row['order_num'] == $value['order_num'] && $value['list_employee_id'] == getCurEmployee() && $this->row['request_status'] == 1 && $value['list_status'] == 0){?>
                                        <a href="javascript:void(0)" class="card-toolbar-btn btn btn-xs radius-1 btn-success mx-1px" draggable="false" onclick="showModalList(<?=$this->employee_request_id?>, <?=$value['employee_request_list_id']?>, 2)">
                                            Согласовать
                                        </a>
                                        <a href="javascript:void(0)" class="card-toolbar-btn btn btn-xs radius-1 btn-danger mx-1px" draggable="false" onclick="showModalList(<?=$this->employee_request_id?>, <?=$value['employee_request_list_id']?>, 3)">
                                            Отказать
                                        </a>
                                        <a href="javascript:void(0)" class="card-toolbar-btn btn btn-xs radius-1 btn-secondary mx-1px" draggable="false" onclick="showModalList(<?=$this->employee_request_id?>, <?=$value['employee_request_list_id']?>, 1)">
                                            Добавить исполнителя
                                        </a>
                                    <?}?>
                                </td>
                            </tr>
                            <?
                            $i = $i + 1;
                        }
                    }
                    ?>
                    </tbody>
                </table>
            </div>
            <?
        }?>
    </div>
</div>
<script>
    $(document).ready(function() {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });
    });
    function showModalList(employee_request_id, employee_request_list_id, accept_type){
        $('#modal-container').find('.modal-dialog').addClass('modal-md');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        $('#modal-header-container').append('Ответить на запрос');
        $.ajax({
            type: 'POST',
            url: "/dict/employee-request-list-accept/",
            data: {employee_request_id : employee_request_id, employee_request_list_id : employee_request_list_id, accept_type : accept_type},
            async: true,
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $(".modal").modal('show');
    }
</script>