<?
$this->headTitle('Ждут согласования');
$this->placeholder('page-header')->set("Ждут согласования");
?>

<style>
    .product-img{
        object-fit: contain;
        border: 1px solid #f2f2f2;
        width: 100px;
        height: 100px;
        padding: 3px;
    }
</style>
<div class="row">
    <div class="col-lg-5 p-0">
        <div class="card dcard mb-3" id="card-5" draggable="false" style="">
            <div class="card-body p-0">
                <div class="p-3">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered hover-table" id="type_table">
                            <thead>
                            <tr class="text-primary-d3 text-95 text-center">
                                <th class="py-3 pl-35">ID</th>
                                <th class="text-center">Тип запроса</th>
                                <th class="text-center">Описание</th>
                                <th class="text-center">Дата создания</th>
                                <th class="text-center">Автор</th>
                                <th class="text-center"></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?
                            if(mycount($this->row) > 0){
                                foreach ($this->row as $key => $value){?>
                                    <tr class="bgc-h-orange-l4 text-600">
                                        <td class="text-center"><?=$value['employee_request_list_id']?></td>
                                        <td class="text-center"><?=$value['employee_request_type_name']?></td>
                                        <td class="text-center"><?=$value['description']?></td>
                                        <td class="text-center"><?=$value['date_create']?></td>
                                        <td class="text-center"><?=$value['author']?></td>
                                        <td class="text-center">
                                            <a href="/dict/employee-request-detail/employee_request_id/<?=$value['employee_request_id']?>/" class="btn btn-success btn-xs float-left">
                                                Открыть
                                            </a>
                                        </td>
                                    </tr>
                                <?}
                            }?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
    });

</script>