<div class="modal-body" id="modal_body">
    <form id="list_id">
        <input type="hidden" value="<?=$this->employee_request_id?>" name="employee_request_id">
        <div class="form-group">
            <label class="control-label " for="list_employee_id">Ответственный</label>
            <div>
                <select class="form-control" id="list_employee_id" name="list_employee_id" required>
                    <option value="0">Выберите ответственного</option>
                    <?foreach ($this->row_employee as $value){?>
                        <option value="<?=$value['employee_id']?>"><?=$value['fio']?>(<?=$value['position_name']?>)</option>
                        <?
                    }?>
                </select>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="request_text">Описание задачи</label>
            <textarea id="request_text" name="request_text" style="height: 200px;" class="autosize-transition form-control"></textarea>
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="order_type">Тип очередности</label>
            <div>
                <select class="form-control" id="order_type" name="order_type" required>
                    <option value="1">Последовательно</option>
                    <option value="2">Паралельно</option>
                </select>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-sm px-4 btn-outline-success mb-1" onclick="updListEmployee()">Сохранить</button>
    <button type="button" class="btn btn-sm px-4 btn-outline-danger mb-1" data-dismiss="modal">Закрыть</button>
</div>

<script>
    $(document).ready(function() {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });
        $(".date-picker").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-80:+5"
        });
    });

    function updListEmployee(){
        main_loader_show();
        var send_data = new FormData($("#list_id")[0]);

        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/dict/employee-request-edit/mode/upd-list/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    $('.modal').modal('hide');
                    toastSucces('Успех');
                    location.reload();
                }
                main_loader_hide();
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }

</script>