<div class="card dcard mb-3 loading-widget" id="card-5" draggable="false" style="">
    <div class="card-header">
        <h5 class="card-title text-120 text-primary-d2">
            Статусы
        </h5>
    </div><!-- /.card-header -->
    <div class="card-body p-0">
        <div class="p-3">
            <div class="table-responsive">
                <table class="table table-striped table-bordered hover-table" id="brief_item_table">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Наименование</th>
                        <th>Чтение</th>
                        <th>Редактирование</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?
                    foreach ($this->row as $key => $value){?>
                        <tr>
                            <td class="text-right"><?=$value['mark_type_id']?></td>
                            <td class="text-left"><?=$value['mark_type_name']?></td>
                            <td class="text-center">
                                <input type="checkbox" name="is_read" onclick="updMarkStage(<?=$this->stage_id?>, <?=$value['mark_type_id']?>, 1)" class="input-lg bgc-blue" <?if($value['is_read'] == 1){?>checked=""<?}?>>
                            </td>
                            <td class="text-center">
                                <input type="checkbox" name="is_upd" onclick="updMarkStage(<?=$this->stage_id?>, <?=$value['mark_type_id']?>, 2)" class="input-lg bgc-blue" <?if($value['is_upd'] == 1){?>checked=""<?}?>>
                            </td>
                        </tr>
                        <?
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div><!-- /.card-body -->
</div>
<script>
    function updMarkStage(stage_id, mark_type_id, type){
        main_loader_show();

        $.ajax({
            type: 'POST',
            url: "/dict/stage-mark-list/mode/upd/",
            data:{"mark_type_id" : mark_type_id, "stage_id" : stage_id, "type" : type},
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                    main_loader_hide();
                }
                else{
                    toastSucces('Успех');
                    main_loader_hide();
                }
            }
        });
    }
</script>