<?
$this->headTitle('Тип материала');
$this->placeholder('page-header')->set("Тип материала");
?>

<style>
    .product-img{
        object-fit: contain;
        border: 1px solid #f2f2f2;
        width: 100px;
        height: 100px;
        padding: 3px;
    }
</style>

<input type="hidden" id="reload_type" name="reload_type">
<input type="hidden" id="material_type_id" name="material_type_id">
<div class="hr hr-10 dotted hr-double"></div>
<div class="row">
    <div class="col-lg-5 p-0">
        <div class="card dcard mb-3" id="card-5" draggable="false" style="">
            <div class="card-header">
                <h5 class="card-title text-120 text-primary-d2">
                    Тип материала
                </h5>
                <div class="card-toolbar">
                    <div class="card-toolbar no-border">
                        <a href="javascript:void(0)" class="card-toolbar-btn btn btn-sm radius-1 btn-outline-success mx-2px" draggable="false" onclick="showModal(0)">
                            <i class="fas fa-plus w-2 mx-1px"></i>
                        </a>
                    </div>
                </div>
            </div><!-- /.card-header -->
            <div class="card-body p-0">
                <div class="p-3">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered hover-table" id="type_table">
                            <thead>
                            <tr class="text-primary-d3 text-95 text-center">
                                <th class="py-3 pl-35">ID</th>
                                <th class="text-center">Наименование</th>
                                <th class="text-center">Код</th>
                                <th class="text-center"></th>
                            </tr>
                            </thead>

                            <tbody>
                            <?
                            if(mycount($this->row) > 0){
                                foreach ($this->row as $key => $value){?>
                                    <tr class="bgc-h-orange-l4 text-600">
                                        <td class="text-center"><?=$value['material_type_id']?></td>
                                        <td class="text-center"><?=$value['material_type_name']?></td>
                                        <td class="text-center"><?=$value['material_type_code']?></td>
                                        <td class="pr-35 text-center" style="white-space: nowrap">
                                            <a href="javascript:void(0);" onclick="showModal(<?=$value['material_type_id']?>)" class="mx-2px btn radius-1 border-2 btn-xs btn-brc-tp btn-light-secondary btn-h-lighter-success btn-a-lighter-warning">
                                                <i class="fa fa-pencil-alt"></i>
                                            </a>
                                            <a href="javascript:void(0);" onclick="del_material_type(<?=$value['material_type_id']?>,'<?=$value['material_type_name']?>', this)" class="mx-2px btn radius-1 border-2 btn-xs btn-brc-tp btn-light-secondary btn-h-lighter-danger btn-a-lighter-danger">
                                                <i class="fa fa-trash-alt"></i>
                                            </a>
                                        </td>
                                    </tr>
                                <?}
                            }?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-7">
        <div id="item_list">

        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
    });

    function showItemTable(material_type_id){
        $("#item_list").load("/dict/material-form/", {material_type_id: material_type_id});
    }
    function showItem(material_type_id, ob){
        $('#reload_type').attr('value', 'all');
        $('#material_type_id').val(material_type_id);
        $('#type_table tbody tr').removeClass('selected-td');
        $(ob).closest('tr').addClass('selected-td');
        showItemTable(material_type_id);
    }
    function showModal(material_type_id){
        $('#modal-container').find('.modal-dialog').addClass('modal-md');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        $('#modal-header-container').append('Редактирование');
        $.ajax({
            type: 'POST',
            url: "/dict/material-type-edit/",
            data: {material_type_id : material_type_id},
            async: true,
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $(".modal").modal('show');
    }

    function materialItemEdit(material_id){
        $('#modal-container').find('.modal-dialog').addClass('modal-sm');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        $('#modal-header-container').append('Редактирование материала');

        var material_type_id = $('#material_type_id').val()
        if(material_type_id == 0){
            alert('Выберите тип!');
            return;
        }
        $.ajax({
            type: 'POST',
            url: "/dict/material-edit/",
            data:{
                material_type_id: material_type_id,
                material_id: material_id
            },
            async: true,
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $(".modal").modal('show');
    }
    function del_material_type(material_type_id, material_type_name, ob){
        if (!confirm("Вы действительно хотите удалить тип материала " + material_type_name + " ?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/dict/material-type-list/mode/del/material_type_id/" + material_type_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Тип ' + material_type_name + ' удален');
                    $(ob).closest("tr").remove();
                }
            }
        });
    }

    function startReload() {
        if($('#reload_type').val() == 'all'){
            $('.loading-widget').aceCard('reload');
            $('#reload_type').attr('value', '');
        }else if($('#reload_type').val() == 'menu'){
            $('#menu_widget').aceCard('reload');
            $('#reload_type').attr('value', '');
        }
    }

    function stopReload() {
        $('.loading-widget').aceCard('stopLoading');
    }

    $(document).ajaxStart(function() {
        startReload();
    });

    $(document).ajaxStop(function() {
        stopReload();
    });
</script>