<div class="card dcard mb-3 loading-widget" id="card-5" draggable="false" style="">
    <div class="card-header">
        <h5 class="card-title text-120 text-primary-d2">
            Материалы
        </h5>
        <div class="card-toolbar">
            <div class="card-toolbar no-border">
                <a href="javascript:void(0)" class="card-toolbar-btn btn btn-sm radius-1 btn-outline-success mx-2px" draggable="false" onclick="showModal(<?=$this->material_id?>)">
                    <i class="fas fa-plus w-2 mx-1px"></i>
                </a>
            </div>
        </div>
    </div><!-- /.card-header -->
    <div class="card-body p-0">
        <div class="p-3">
            <div class="table-responsive">
                <table class="table table-striped table-bordered hover-table" id="brief_item_table">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Наименование</th>
                        <th>Код</th>
                        <th>Фото</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?
                    foreach ($this->row as $key => $value){?>
                        <tr>
                            <td class="text-right"><?=$value['material_id']?></td>
                            <td class="text-left"><?=$value['material_name']?></td>
                            <td class="text-left"><?=$value['material_code']?></td>
                            <td class="text-left"><?=$value['material_code']?></td>
                            <td class="text-center">
                                <a href="#" class="mx-2px btn radius-1 border-2 btn-xs btn-brc-tp btn-light-secondary btn-h-lighter-success btn-a-lighter-success" onclick="materialItemEdit(<?=$value['material_id']?>)">
                                    <i class="fa fa-pencil-alt"></i>
                                </a>
                            </td>
                            <td class="text-center">
                                <a href="#" class="mx-2px btn radius-1 border-2 btn-xs btn-brc-tp btn-light-secondary btn-h-lighter-danger btn-a-lighter-danger" onclick="delMaterial(<?=$value['material_id']?>, this)">
                                    <i class="fa fa-trash-alt"></i>
                                </a>
                            </td>
                        </tr>
                        <?
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div><!-- /.card-body -->
</div>
<script>
    function delMaterial(material_id, ob){
        if (!confirm('Вы действительно хотите удалить?')) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/dict/material-list/mode/del/",
            data:{"material_id" : material_id},
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Материал удален');
                    $(ob).closest("tr").remove();
                }
            }
        });
    }
</script>