<div class="modal-body" id="modal_body">
    <form id="price_id">
        <input type="hidden" value="<?=$this->material_id?>" name="material_id">
        <?
        $arr_package = str_replace("{", "",  $this->row['package_id_arr']);
        $arr_package = str_replace("}", "",  $arr_package);
        $arr_package = explode(',', $arr_package);
        ?>
        <div class="form-group">
            <label class="control-label " for="package_id_arr">Пакеты</label>
            <button type="button" class="chosen-toggle-status select">Выбрать все</button>
            <button type="button" class="chosen-toggle-status deselect">Снять выборку</button>
            <div class="no-padding">

                <select class="chosen-select form-control" id="package_id_arr" data-placeholder="Выберите статус..." name="package_id_arr[]" multiple>
                    <?
                    if(mycount($this->row_package) > 0){
                        foreach ($this->row_package as $key => $value){?>
                            <option value="<?=$value['package_id']?>" <?=is_selected_html_multiple($value['package_id'], $arr_package)?>><?=$value['package_name']?></option>
                            <?
                        }
                    }?>
                </select>
            </div>
            <div class="clearfix"></div>
        </div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-sm px-4 btn-outline-success mb-1" onclick="updMaterialPackage()">Сохранить</button>
    <button type="button" class="btn btn-sm px-4 btn-outline-danger mb-1" data-dismiss="modal">Закрыть</button>
</div>

<script>
    $(document).ready(function() {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });
        $(".date-picker").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-80:+5"
        });
        $('.chosen-toggle-status').each(function(index) {
            $(this).on('click', function(){
                $('#package_id_arr').find('option').prop('selected', $(this).hasClass('select')).parent().trigger('chosen:updated');
            });
        });
    });

    function updMaterialPackage(){
        main_loader_show();
        var send_data = new FormData($("#price_id")[0]);

        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/dict/material-list/mode/upd-package/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    $('.modal').modal('hide');
                    toastSucces('Успех');
                    location.reload();
                }
                main_loader_hide();
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }

</script>