<div class="modal-body" id="modal_body">
    <form id="price_id">
        <input type="hidden" value="<?=$this->material_id?>" name="material_id">

        <div class="form-group">
            <label class="control-label " for="price">Цена</label>
            <input type="number" step="any" id="price" placeholder="Цена" class="form-control" value="<?=$this->row['price'] ?? null?>" name="price">
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="date_start">Начало</label>
            <input type="text" style="width: 166px; height: 34px" id="date_start" name="date_start" placeholder="Начало" class="form-control date-picker" value="<?=$this->row['date_start'] ?? null?>" autocomplete="off">
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="date_end">Конец</label>
            <input type="text" style="width: 166px; height: 34px" id="date_end" name="date_end" placeholder="Конец" class="form-control date-picker" value="<?=$this->row['date_end'] ?? null?>" autocomplete="off">
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-sm px-4 btn-outline-success mb-1" onclick="updMaterialPrice()">Сохранить</button>
    <button type="button" class="btn btn-sm px-4 btn-outline-danger mb-1" data-dismiss="modal">Закрыть</button>
</div>

<script>
    $(document).ready(function() {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });
        $(".date-picker").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-80:+5"
        });
    });

    function updMaterialPrice(){
        main_loader_show();
        var send_data = new FormData($("#price_id")[0]);

        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/dict/material-list/mode/upd-price/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    $('.modal').modal('hide');
                    toastSucces('Успех');
                    location.reload();
                }
                main_loader_hide();
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }

</script>