<?
$this->headTitle('Редактирование продукта');
$this->placeholder('page-header')->set("Редактирование продукта");
?>

<style>
    .product-img{
        object-fit: contain;
        border: 1px solid #f2f2f2;
        width: 100px;
        height: 100px;
    }
</style>
<div class="hr hr-10 dotted hr-double"></div>
<div class="row">
    <div class="col-lg-12 p-0" id="load">
        <div class="card dcard mb-3" id="sp_table" draggable="false" style="">
            <div class="card-body">
                <form id="form_id" method="post">
                    <?
                    if (strlen($this->globalError) > 0) {?>
                        <div class="alert alert-danger">
                            <?=$this->globalError?>
                        </div>
                        <?
                    }?>

                    <h4>Основное</h4>
                    <hr>
                    <input type="hidden" value="<?=$this->product_id?>" name="product_id">

                    <div class="form-group">
                        <label class="control-label " for="stock_name">Наименование</label>
                        <input type="text" id="stock_name" placeholder="Наименование" class="form-control col-lg-4" value="<?=$this->row['product_name'] ?? null?>" name="product_name">
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <label class="control-label " for="product_desc">Описание</label>
                        <textarea class="form-control col-lg-4" id="id-textarea-limit2" name="product_desc"><?=$this->row['product_desc'] ?? null?></textarea>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <label class="control-label " for="is_active">Бренд</label>
                        <div>
                            <select class="chosen-select form-control col-lg-4" name="brand_id" id="brand_id" data-placeholder="Выберите бренд...">
                                <option value="0"> </option>
                                <?
                                if(mycount($this->row_brand) > 0){
                                    foreach ($this->row_brand as $key => $value){?>
                                        <option <?=is_selected_html($this->row['brand_id'] ?? 0, $value['brand_id'])?> value="<?=$value['brand_id']?>"><?=$value['brand_name']?></option>
                                    <?}
                                }?>
                            </select>
                        </div>
                        <div class="clearfix"></div>
                    </div>

                    <div class="form-group">
                        <label class="control-label " for="price">Цена</label>
                        <input type="text" id="price" placeholder="Цена" class="form-control col-lg-4    number-input" value="<?=$this->row['price'] ?? null?>" name="price">
                        <div class="clearfix"></div>
                    </div>

                    <div class="form-group">
                        <label class="control-label " for="price_old">Старая цена</label>
                        <input type="text" id="price_old" placeholder="Старая цена" class="form-control col-lg-4 number-input" value="<?=$this->row['price_old'] ?? null?>" name="price_old">
                        <div class="clearfix"></div>
                    </div>

                    <?
                        $arr_category = str_replace("{", "",  $this->row['category_id_arr']);
                        $arr_category = str_replace("}", "",  $arr_category);
                        $arr_category = explode(',', $arr_category);
                    ?>
                    <div class="form-group">
                        <label class="control-label " for="is_active">Категории</label>
                        <div id="select2-parent">
                            <select multiple class="select2 form-control col-lg-4" name="category_id_arr[]" id="category_id_arr" data-placeholder="Выберите категорию...">
                                <option value="0"> </option>
                                <?
                                if(mycount($this->row_category) > 0){
                                    foreach ($this->row_category as $key => $value){?>
                                        <option value="<?=$value['category_id']?>" <?=is_selected_html_multiple($value['category_id'], $arr_category)?>><?=$value['category_name']?></option>
                                    <?}
                                }?>
                            </select>
                        </div>
                        <div class="clearfix"></div>
                    </div>

                    <?
                        $arr_tags = str_replace("{", "",  $this->row['tag_id_arr']);
                        $arr_tags = str_replace("}", "",  $arr_tags);
                        $arr_tags = explode(',', $arr_tags);
                    ?>
                    <div class="form-group">
                        <label class="control-label " for="tag_id_arr">Тэги</label>
                        <div id="select3-parent">
                            <select multiple class="select3 form-control col-lg-4" name="tag_id_arr[]" id="tag_id_arr" data-placeholder="Выберите тэг...">
                                <option value="0"> </option>
                                <?
                                if(mycount($this->row_tag) > 0){
                                    foreach ($this->row_tag as $key => $value){?>
                                        <option value="<?=$value['tag_id']?>" <?=is_selected_html_multiple($value['tag_id'], $arr_tags)?>><?=$value['tag_name']?></option>
                                    <?}
                                }?>
                            </select>
                        </div>
                        <div class="clearfix"></div>
                    </div>

                    <div class="form-group">
                        <label class="control-label " for="is_avail">Доступен</label>
                        <div>
                            <select class="form-control col-lg-4" id="is_avail" name="is_avail" required>
                                <option value="0" <?=is_selected_html(0, $this->row['is_avail'] ?? null)?>>Нет</option>
                                <option value="1" <?=is_selected_html(1, $this->row['is_avail'] ?? null)?>>Да</option>
                            </select>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <?if($this->product_id <> 0){?>
                        <br>
                        <h4>Фото продукта</h4>
                        <hr>
                        <div class="py-3 mt-3" id="gallery">
                            <div class="pos-rel d-style my-3 radius-1 shadow-sm overflow-hidden bgc-purple-m3" style="width: 100px;">
                                <a href="#" class="show-lightbox">
                                    <img src="assets/image/gallery/thumb6.jpg" onerror="imgErrorHref(this);" alt="картинка" class="radius-1 mb-1 mb-sm-0 mr-3 d-none d-sm-block w-100 d-zoom-2 product-img"/>
                                </a>
                                <div class="mr-hover position-tr h-100 bgc-black-tp4 p-25">
                                    <div class="d-flex flex-md-column justify-content-center action-buttons text-110">
                                        <a href="#" class="my-2">
                                            <i class="fa fa-times text-danger-l1"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?}?>
                    <a href="/dict/product-list/" class="btn btn-danger pull-right"  name="save">Назад</a>
                    <button type="submit" class="btn btn-success pull-right"  name="save">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe-ui-default.min.js"></script>
<script>
    $(document).ready(function() {
        $('.select2').select2({
            allowClear: true,
            dropdownParent: $('#select2-parent'),
        });

        $('.select3').select2({
            allowClear: true,
            dropdownParent: $('#select3-parent'),
        });
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });
        $('input.number-input').on('input', function() {
            var value = $(this).val();
            var regex = /^\d*\.?\d+$/;
            if (!regex.test(value)) {
                $(this).val(value.replace(/[^0-9\.]/g, ''));
            }
        });
    });

</script>
