<?
$this->headTitle('Продукты');
$this->placeholder('page-header')->set("Продукты");
?>

<style>
    .product-img{
        object-fit: contain;
        border: 1px solid #f2f2f2;
        width: 100px;
        height: 100px;
        padding: 3px;
    }
</style>
<div class="hr hr-10 dotted hr-double"></div>
<div class="row">
    <div class="col-lg-12 p-0" id="load">
        <div class="pos-rel ml-sm-auto order-last order-sm-0 float-left" style="margin-bottom: 5px;">
            <i class="fa fa-search position-lc ml-25 text-primary-m1"></i>
            <input type="text" class="form-control w-100 pl-45 radius-1 brc-primary-m4" id="sp_search" placeholder="Быстрый поиск ...">
        </div>
        <a href="/dict/product-edit/product_id/0/" class="btn btn-success float-left" style="margin-left: 5px;">
            <i class="ace-icon fa fa-plus bigger-125"></i>
            Добавить
        </a>
        <div class="clearfix"></div>

        <div class="card dcard mb-3" id="product_table" draggable="false" style="">
            <div class="card-body p-0">
                <div class="p-3">
                    <div class="card-body p-0 table-responsive">
                        <table class="table mb-1">
                            <thead>
                            <tr class="text-primary-d3 text-95 text-center">
                                <th class="py-3 pl-35">ID</th>
                                <th class="text-center">Наименование</th>
                                <th class="text-center" style="width: 100px;">Фото</th>
                                <th class="text-center">Бренд</th>
                                <th class="text-center">Описание</th>
                                <th class="text-center">Категория</th>
                                <th class="text-center">Тэги</th>
                                <th class="text-center">Цена</th>
                                <th class="text-center">Доступность</th>
                                <th class="text-center"></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?
                            if(mycount($this->row) > 0){
                                foreach ($this->row as $key => $value){?>
                                    <tr class="bgc-h-orange-l4 text-600">
                                        <td class="text-right"><?=$value['product_id']?></td>
                                        <td class="text-left"><?=$value['product_name']?></td>
                                        <td class="text-center">
                                            <img src="<?=$value['img_thumb_url']?>" onerror="imgErrorHref(this);" alt="картинка" class="radius-1 mb-1 mb-sm-0 mr-3 d-none d-sm-block product-img"/>
                                        </td>
                                        <td class="text-left"><?=$value['brand_name']?></td>
                                        <td class="text-left"><?=$value['product_desc']?></td>
                                        <td class="text-left"><?=$value['category_list']?></td>
                                        <td class="text-left"><?=$value['tag_list']?></td>
                                        <td class="text-right"><?=tenge_text($value['price'])?></td>
                                        <td class="text-center">
                                            <input type="checkbox" id="is_avail" class="ace-switch ace-switch-bars bgc-success-d2 ml-2" <?if($value['is_avail'] == 'checked'){?>checked<?}?> onchange="set_is_avail(<?=$value['product_id']?>, this)">
                                        </td>
                                        <td class="pr-35 text-center" style="white-space: nowrap">
                                            <a href="/dict/product-edit/product_id/<?=$value['product_id']?>/" class="mx-2px btn radius-1 border-2 btn-xs btn-brc-tp btn-light-secondary btn-h-lighter-success btn-a-lighter-warning">
                                                <i class="fa fa-pencil-alt"></i>
                                            </a>
                                            <a href="javascript:void(0);" onclick="delProduct(<?=$value['product_id']?>,'<?=$value['product_name']?>', this)" class="mx-2px btn radius-1 border-2 btn-xs btn-brc-tp btn-light-secondary btn-h-lighter-danger btn-a-lighter-danger">
                                                <i class="fa fa-trash-alt"></i>
                                            </a>
                                        </td>
                                    </tr>
                                <?}
                            }?>
                            </tbody>
                        </table>
                    </div><!-- /.card-body -->
                </div>
            </div><!-- /.card-body -->
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $("#sp_search").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#product_table tbody tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });

    function delProduct(product_id, product_name, ob){
        if (!confirm("Вы действительно хотите удалить продукт " + product_name + " ?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/dict/product-list/mode/del/product_id/" + product_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Продукт ' + product_name + ' удалена');
                    $(ob).closest("tr").remove();
                }
            }
        });
    }

    function set_is_avail(product_id, ob) {
        var isChecked = $(ob).is(':checked');

        $.ajax({
            type: 'POST',
            url: "/dict/product-list/mode/set-avail/",
            data:{product_id: product_id},
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                    $(ob).prop('checked', false);
                }else{
                    if(isChecked != false){
                        toastSucces('Продукт доступен');
                    }else{
                        toastSucces('Продукт недоступен');
                    }
                }
            }
        });
    }

</script>