<?
$this->headTitle('Статусы этапов');
$this->placeholder('page-header')->set("Статусы этапов");
?>

<style>
    .product-img{
        object-fit: contain;
        border: 1px solid #f2f2f2;
        width: 100px;
        height: 100px;
        padding: 3px;
    }
</style>

<input type="hidden" id="reload_type" name="reload_type">
<input type="hidden" id="stage_id" name="stage_id">
<div class="hr hr-10 dotted hr-double"></div>
<div class="row">
    <div class="col-lg-3 p-0">
        <div class="card dcard mb-3" id="card-5" draggable="false" style="">
            <div class="card-header">
                <h5 class="card-title text-120 text-primary-d2">
                    Этапы
                </h5>
            </div><!-- /.card-header -->
            <div class="card-body p-0">
                <div class="p-3">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered hover-table" id="type_table">
                            <thead>
                            <tr class="text-primary-d3 text-95 text-center">
                                <th class="py-3 pl-35">ID</th>
                                <th class="text-center">Этап</th>
                            </tr>
                            </thead>

                            <tbody>
                            <?
                            if(mycount($this->row) > 0){
                                foreach ($this->row as $key => $value){?>
                                    <tr class="bgc-h-orange-l4 text-600">
                                        <td class="text-center"><?=$value['stage_id']?></td>
                                        <td onclick="showMark(<?=$value['stage_id']?>, this)" class="text-center"><?=$value['stage_name']?></td>
                                    </tr>
                                <?}
                            }?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div id="mark_list">

        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
    });

    function showMarkTable(stage_id){
        $("#mark_list").load("/dict/mark-type-form/", {stage_id: stage_id});
    }
    function showMark(stage_id, ob){
        $('#reload_type').attr('value', 'all');
        $('#stage_id').val(stage_id);
        $('#type_table tbody tr').removeClass('selected-td');
        $(ob).closest('tr').addClass('selected-td');
        showMarkTable(stage_id);
    }
    function startReload() {
        if($('#reload_type').val() == 'all'){
            $('.loading-widget').aceCard('reload');
            $('#reload_type').attr('value', '');
        }else if($('#reload_type').val() == 'menu'){
            $('#menu_widget').aceCard('reload');
            $('#reload_type').attr('value', '');
        }
    }

    function stopReload() {
        $('.loading-widget').aceCard('stopLoading');
    }

    $(document).ajaxStart(function() {
        startReload();
    });

    $(document).ajaxStop(function() {
        stopReload();
    });
</script>