<div class="card dcard mb-3 loading-widget" id="card-5" draggable="false" style="">
    <div class="card-header">
        <h5 class="card-title text-120 text-primary-d2">
            Продукты акции
        </h5>
        <div class="card-toolbar">
            <div class="card-toolbar no-border">
                <a href="javascript:void(0)" class="card-toolbar-btn btn btn-sm radius-1 btn-outline-success mx-2px" draggable="false" onclick="showModalStockProduct(0)">
                    <i class="fas fa-plus w-2 mx-1px"></i>
                </a>
            </div>
        </div>
    </div><!-- /.card-header -->
    <div class="card-body p-0">
        <div class="p-3">
            <div class="table-responsive">
                <table class="table table-striped table-bordered hover-table" id="category_table">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Продукт</th>
                        <th>Фото</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?
                    foreach ($this->row as $key => $value){?>
                        <tr>
                            <td class="text-right"><?=$value['product_id']?></td>
                            <td class="text-left"><?=$value['product_name']?></td>
                            <td class="text-left">
                                <img src="<?=$value['img_thumb_url']?>" onerror="imgErrorHref(this);" alt="картинка" class="radius-1 mb-1 mb-sm-0 mr-3 d-none d-sm-block product-img"/>
                            </td>
                            <td class="text-center">
                                <a href="#" class="mx-2px btn radius-1 border-2 btn-xs btn-brc-tp btn-light-secondary btn-h-lighter-danger btn-a-lighter-danger" onclick="delStockProduct(<?=$value['product_stock_id']?>, this)">
                                    <i class="fa fa-trash-alt"></i>
                                </a>
                            </td>
                        </tr>
                        <?
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div><!-- /.card-body -->
</div>
<script>

    function delStockProduct(product_stock_id, ob){
        if (!confirm('Вы действительно хотите удалить?')) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/dict/stock-list/mode/del-product/",
            data:{"product_stock_id" : product_stock_id},
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Продукт удален');
                    $(ob).closest("tr").remove();
                }
            }
        });
    }

    function set_is_active(category_id, ob) {
        var isChecked = $(ob).is(':checked');

        $.ajax({
            type: 'POST',
            url: "/dict/category-form/mode/set-active/",
            data:{category_id: category_id},
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                    $(ob).prop('checked', false);
                }else{
                    if(isChecked != false){
                        toastSucces('Бренд активный');
                    }else{
                        toastSucces('Бренд неактивный');
                    }
                }
            }
        });
    }
</script>