<div class="modal-body" id="modal_body">
    <form id="form_id">
        <input type="hidden" value="<?=$this->stock_id?>" name="stock_id">

        <div class="form-group">
            <label class="control-label " for="stock_name">Наименование</label>
            <input type="text" id="stock_name" placeholder="Наименование" class="form-control" value="<?=$this->row['stock_name'] ?? null?>" name="stock_name">
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="discount_percent">Фото</label>
            <div class="form-control no-padding">
                <input type="file" name="upload" id="upload" >
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="discount_percent">Скидка</label>
            <input type="text" id="discount_percent" placeholder="Скидка" class="form-control number-input" value="<?=$this->row['discount_percent'] ?? null?>" name="discount_percent">
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="stock_start">Дата начала</label>
            <input type="text" id="stock_start" placeholder="Дата начала" class="form-control datepicker" value="<?=$this->stock_start?>" name="stock_start">
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="stock_end">Дата окончания</label>
            <input type="text" id="stock_end" placeholder="Дата окончания" class="form-control datepicker" value="<?=$this->stock_end?>" name="stock_end">
            <div class="clearfix"></div>
        </div>

        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-sm px-4 btn-outline-success mb-1" onclick="updStock()">Сохранить</button>
    <button type="button" class="btn btn-sm px-4 btn-outline-danger mb-1" data-dismiss="modal">Закрыть</button>
</div>

<script>
    $(document).ready(function() {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });

        $('input.number-input').on('input', function() {
            var value = $(this).val();
            var regex = /^\d*\.?\d+$/;
            if (!regex.test(value)) {
                $(this).val(value.replace(/[^0-9\.]/g, ''));
            }
        });
        $(".datepicker").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-100:+0"
        });
    });

    function updStock(){
        main_loader_show();
        var send_data = new FormData($("#form_id")[0]);

        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/dict/stock-list/mode/upd/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    $('.modal').modal('hide');
                    toastSucces('Успех');
                    location.reload();
                }
                main_loader_hide();
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }
</script>