<?
$this->headTitle('Акция');
$this->placeholder('page-header')->set("Акция");
?>

<input type="hidden" id="reload_type" name="reload_type">
<input type="hidden" id="stock_id" name="stock_id">
<style>
    .product-img{
        object-fit: contain;
        border: 1px solid #f2f2f2;
        width: 100px;
        height: 100px;
        padding: 3px;
    }
</style>
<div class="hr hr-10 dotted hr-double"></div>
<div class="row">
    <div class="col-lg-12 p-0" id="load">
        <div class="pos-rel ml-sm-auto order-last order-sm-0 float-left" style="margin-bottom: 5px;">
            <i class="fa fa-search position-lc ml-25 text-primary-m1"></i>
            <input type="text" class="form-control w-100 pl-45 radius-1 brc-primary-m4" id="sp_search" placeholder="Быстрый поиск ...">
        </div>
        <button type="button" name="add" class="btn btn-success float-left" style="margin-left: 5px;" onclick="showModal(0)" >
            <i class="ace-icon fa fa-plus bigger-125"></i>
            Добавить
        </button>
        <div class="clearfix"></div>
    </div>
    <div class="col-lg-7" style="padding-left: 0;">
        <div class="card dcard mb-3" id="sp_table" draggable="false" style="">
            <div class="card-body p-0">
                <div class="p-3">
                    <div class="card-body p-0 table-responsive">
                        <table class="table mb-1" id="stock_table">
                            <thead>
                            <tr class="text-primary-d3 text-95 text-center">
                                <th class="py-3 pl-35">ID</th>
                                <th class="text-center">Наименование</th>
                                <th class="text-center">Фото</th>
                                <th class="text-center">Скидка</th>
                                <th class="text-center">Дата начала</th>
                                <th class="text-center">Дата окончания</th>
                                <th class="text-center"></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?
                            if(mycount($this->row) > 0){
                                foreach ($this->row as $key => $value){?>
                                    <tr class="bgc-h-orange-l4 text-600">
                                        <td class="text-center"><?=$value['stock_id']?></td>
                                        <td class="text-center" onclick="showStock(<?=$value['stock_id']?>, this)"><?=$value['stock_name']?></td>
                                        <td class="text-center" onclick="showStock(<?=$value['stock_id']?>, this)">
                                            <img src="<?=$value['stock_img']?>" onerror="imgErrorHref(this);" alt="картинка" class="radius-1 mb-1 mb-sm-0 mr-3 d-none d-sm-block product-img"/>
                                        </td>
                                        <td class="text-center" onclick="showStock(<?=$value['stock_id']?>, this)"><?=$value['discount_percent']?></td>
                                        <td class="text-center" onclick="showStock(<?=$value['stock_id']?>, this)"><?=$value['stock_start']?></td>
                                        <td class="text-center" onclick="showStock(<?=$value['stock_id']?>, this)"><?=$value['stock_end']?></td>
                                        <td class="pr-35 text-center" style="white-space: nowrap">
                                            <a href="javascript:void(0);" onclick="showModal(<?=$value['stock_id']?>)" class="mx-2px btn radius-1 border-2 btn-xs btn-brc-tp btn-light-secondary btn-h-lighter-success btn-a-lighter-warning">
                                                <i class="fa fa-pencil-alt"></i>
                                            </a>
                                            <a href="javascript:void(0);" onclick="delStock(<?=$value['stock_id']?>,'<?=$value['stock_name']?>', this)" class="mx-2px btn radius-1 border-2 btn-xs btn-brc-tp btn-light-secondary btn-h-lighter-danger btn-a-lighter-danger">
                                                <i class="fa fa-trash-alt"></i>
                                            </a>
                                        </td>
                                    </tr>
                                <?}
                            }?>
                            </tbody>
                        </table>
                    </div><!-- /.card-body -->
                </div>
            </div><!-- /.card-body -->
        </div>
    </div>
    <div class="col-lg-4">
        <div id="product_stock_list">

        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('#modal').on('shown.bs.modal', function (e) {
            $(document).keypress(function(e) {
                var keycode = (e.keyCode ? e.keyCode : e.which);
                if (keycode == '13') {
                    updShop();
                }
            });
        });

        $("#sp_search").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#sp_table tbody tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
    function showStockTable(stock_id){
        $("#product_stock_list").load("/dict/stock-product-form/", {stock_id: stock_id});
    }
    function showModalStockProduct(product_id){
        $('#modal-container').find('.modal-dialog').addClass('modal-sm');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        $('#modal-header-container').append('Добавить продукт');

        var stock_id = $('#stock_id').val();
        if(stock_id == 0){
            alert('Выберите акцию!');
            return;
        }
        $.ajax({
            type: 'POST',
            url: "/dict/stock-product-edit/",
            data:{
                stock_id: stock_id,
                product_id: product_id
            },
            async: true,
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $(".modal").modal('show');
    }
    function showStock(stock_id, ob){
        $('#reload_type').attr('value', 'all');
        $('#stock_id').val(stock_id);
        $('#stock_table tbody tr').removeClass('selected-td');
        $(ob).closest('tr').addClass('selected-td');
        showStockTable(stock_id);
    }

    function startReload() {
        if($('#reload_type').val() == 'all'){
            $('.loading-widget').aceCard('reload');
            $('#reload_type').attr('value', '');
        }else if($('#reload_type').val() == 'menu'){
            $('#menu_widget').aceCard('reload');
            $('#reload_type').attr('value', '');
        }
    }

    function stopReload() {
        $('.loading-widget').aceCard('stopLoading');
    }

    $(document).ajaxStart(function() {
        startReload();
    });

    $(document).ajaxStop(function() {
        stopReload();
    });
    function showModal(stock_id){
        $('#modal-container').find('.modal-dialog').addClass('modal-md');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        $('#modal-header-container').append('Редактирование акции');
        $.ajax({
            type: 'POST',
            url: "/dict/stock-edit/",
            data: {stock_id : stock_id},
            async: true,
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $(".modal").modal('show');
    }

    function delStock(stock_id, stock_name, ob){
        if (!confirm("Вы действительно хотите удалить акцию " + stock_name + " ?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/dict/stock-list/mode/del/stock_id/" + stock_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Акция ' + stock_name + ' удалена');
                    $(ob).closest("tr").remove();
                }
            }
        });
    }
</script>