<style>
    .modal-body .chosen-container {
        width: 100% !important;
    }
</style>
<div class="modal-body" id="modal_body">
    <form id="form_id">
        <input type="hidden" value="<?=$this->stock_id?>" name="stock_id">
        <div class="form-group">
            <label class="control-label " for="product_id">Продукт</label>
            <div>
                <select class="chosen-select form-control" id="product_id" name="product_id" data-placeholder="Выберите продукт...">
                    <option value="0"> </option>
                    <?
                    if(mycount($this->row_product) > 0){
                        foreach($this->row_product as $key => $value){?>
                            <option value="<?=$value['product_id']?>" <?if($this->row['product_id'] == $value['product_id']){echo ' selected';}?>><?=$value['product_name']?>(<?=$value['brand_name']?>)</option>
                            <?
                        }
                    }?>
                </select>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-sm px-4 btn-outline-success mb-1" onclick="updProductStock()">Сохранить</button>
    <button type="button" class="btn btn-sm px-4 btn-outline-danger mb-1" data-dismiss="modal">Закрыть</button>
</div>
<script>
    $(document).ready(function() {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });
    });

    function updProductStock(){
        var send_data = $('#form_id').serializeArray();
        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/dict/stock-list/mode/upd-product/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Продукт успешно добавлен');
                    showStockTable($('#stock_id').val());
                    $(".modal").modal('hide');
                }
            }
        });
    }
</script>