<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
    <base href="../" />

    <title>Авторизация - iHealth</title>

    <!-- include common vendor stylesheets & fontawesome -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/fontawesome.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/regular.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/brands.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/solid.min.css">
    <!-- include vendor stylesheets used in "Login" page. see "/views//pages/partials/page-login/@vendor-stylesheets.hbs" -->
    <!-- include fonts -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600&display=swap">
    <!-- ace.css -->
    <link rel="stylesheet" type="text/css" href="/dist/css/ace.min.css">
    <!-- favicon -->
    <link rel="icon" type="image/png" href="/assets/favicon.ico" />
    <!-- "Login" page styles, specific to this page for demo only -->
    <style>
        .body-container {
            background-image: linear-gradient(#6baace, #264783);
            background-attachment: fixed;
            background-repeat: no-repeat;
        }

        .carousel-item>div {
            height: 100%;
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
        }

        /* these rules are used to make sure in mobile devices, tab panes are not all the same height (for example 'forgot' pane is not as tall as 'signup' pane) */

        @media (max-width: 1199.98px) {
            .tab-sliding .tab-pane:not(.active) {
                max-height: 0 !important;
            }

            .tab-sliding .tab-pane.active {
                min-height: 80vh;
                max-height: none !important;
            }
        }
        .rd-color{
            color: #69AF80 !important;
        }
    </style>
</head>

<body>
<div class="body-container">
    <div class="main-container container bgc-transparent">
        <div class="main-content minh-100 justify-content-center">
            <div class="p-2 p-md-4">
                <div class="row justify-content-center" id="row-1">
                    <div class="bgc-white shadow radius-1 overflow-hidden col-12 col-lg-6 col-xl-5">
                        <div class="row" id="row-2">
                            <div id="id-col-main" class="col-12 py-lg-5 bgc-white px-0">
                                <div class="tab-content tab-sliding border-0 p-0" data-swipe="right">

                                    <div class="tab-pane active show mh-100 px-3 px-lg-0 pb-3" id="id-tab-login">
                                        <!-- show this in desktop -->
                                        <!-- show this in mobile device -->
                                        <div class="text-secondary-m1 my-4 text-center">
                                            <a href="javascript:void(0)">
                                                <i class="fas fa-leaf rd-color text-200 mb-4"></i>
                                            </a>
                                            <h1 class="text-170">
                                                <span class="rd-color">
                                                    iHealth <span class="text-80 text-dark-tp3">Application</span>
                                                </span>
                                            </h1>
                                            Добро пожаловать
                                        </div>
                                        <form autocomplete="off" method="post" class="form-row mt-4">
                                            <?
                                            if(isset($this->error)){?>
                                                <div class="alert d-flex bgc-red-l3 brc-success-m4 border-0 p-0 col-sm-10 offset-sm-1 col-md-8 offset-md-2" role="alert">
                                                    <div class="bgc-red px-3 py-1 text-center radius-l-1">
                                                        <span class="fa-2x text-white">
                                                            ⚠ <!-- &#9888; -->
                                                        </span>
                                                    </div>
                                                    <span class="ml-3 align-self-center text-dark-tp3 text-110">
                                                        <?=$this->error?>
                                                    </span>
                                                </div>
                                                <?
                                            }?>
                                            <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2">
                                                <div class="d-flex align-items-center input-floating-label text-blue brc-blue-m2">
                                                    <input placeholder="Логин" type="text" name="login" class="form-control form-control-lg pr-4 shadow-none" id="id-login-username">
                                                    <i class="fa fa-user text-grey-m2 ml-n4"></i>
                                                    <label class="floating-label text-grey-l1 ml-n3" for="id-login-username">
                                                        Логин
                                                    </label>
                                                </div>
                                            </div>


                                            <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 mt-2 mt-md-1">
                                                <div class="d-flex align-items-center input-floating-label text-blue brc-blue-m2">
                                                    <input placeholder="Пароль" type="password" name="password" class="form-control form-control-lg pr-4 shadow-none" id="id-login-password">
                                                    <i class="fa fa-key text-grey-m2 ml-n4"></i>
                                                    <label class="floating-label text-grey-l1 ml-n3" for="id-login-password">
                                                        Пароль
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 text-right text-md-right mt-n2 mb-2">
                                                <a href="#" class="text-primary-m1 text-95" data-toggle="tab" data-target="#id-tab-forgot">
                                                    Забыли пароль?
                                                </a>
                                            </div>
                                            <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2">
                                                <button type="submit" class="btn btn-primary btn-block px-4 btn-bold mt-2 mb-4">
                                                    Войти
                                                </button>
                                            </div>
                                        </form>
                                    </div>

                                    <div class="tab-pane mh-100 px-3 px-lg-0 pb-3" id="id-tab-forgot" data-swipe-prev="#id-tab-login">
                                        <div class="position-tl ml-3 mt-2">
                                            <a href="#" class="btn btn-light-default btn-h-light-default btn-a-light-default btn-bgc-tp" data-toggle="tab" data-target="#id-tab-login">
                                                <i class="fa fa-arrow-left"></i>
                                            </a>
                                        </div>


                                        <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 mt-5 px-0">
                                            <h4 class="pt-4 pt-md-0 text-dark-tp4 border-b-1 brc-grey-l2 pb-1 text-130">
                                                <i class="fa fa-key text-brown-m1 mr-1"></i>
                                                Восстановаление пароля
                                            </h4>
                                        </div>


                                        <form autocomplete="off" class="form-row mt-4">
                                            <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2">
                                                <label class="text-secondary-d3 mb-3">
                                                    Введите свой email
                                                </label>
                                                <div class="d-flex align-items-center">
                                                    <input type="email" class="form-control form-control-lg pr-4 shadow-none" id="id-recover-email" placeholder="Email">
                                                    <i class="fa fa-envelope text-grey-m2 ml-n4"></i>
                                                </div>
                                            </div>

                                            <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 mt-1">
                                                <button type="button" class="btn btn-orange btn-block px-4 btn-bold mt-2 mb-4">
                                                    Продолжить
                                                </button>
                                            </div>
                                        </form>


                                        <div class="form-row w-100">
                                            <div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 d-flex flex-column align-items-center justify-content-center">

                                                <hr class="brc-default-l2 mt-0 mb-2 w-100">

                                                <div class="p-0 px-md-2 text-dark-tp4 my-3">
                                                    <a class="text-blue-d1 text-600 btn-text-slide-x" data-toggle="tab" data-target="#id-tab-login" href="#">
                                                        <i class="btn-text-2 fa fa-arrow-left text-110 align-text-bottom mr-2"></i>Назад
                                                    </a>
                                                </div>

                                            </div>
                                        </div>
                                    </div>

                                </div><!-- .tab-content -->
                            </div>

                        </div><!-- /.row -->

                    </div><!-- /.col -->
                </div><!-- /.row -->

                <div class="d-lg-none my-3 text-white-tp1 text-center">
                    <i class="fas fa-leaf rd-color mr-1 text-110"></i> iHealth © <?=date('Y')?>
                </div>
            </div>
        </div>

    </div>

</div>

<!-- include common vendor scripts used in demo pages -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>
<!-- include vendor scripts used in "Login" page. see "/views//pages/partials/page-login/@vendor-scripts.hbs" -->
<!-- include ace.js -->
<script src="/dist/js/ace.min.js"></script>
<!-- "Login" page script to enable its demo functionality -->
<script>
</script>
</body>
</html>