<style>
    .modal-body .chosen-container {
        width: 100% !important;
    }
</style>
<div class="modal-body" id="modal_body">
    <form id="form_id">
        <input type="hidden" value="<?=$this->user_right_id?>" name="user_right_id">
        <input type="hidden" value="<?=$this->user_right_item_id?>" name="user_right_item_id">
        <div class="form-group">
            <label class="control-label " for="employee_id">Пользователи</label>
            <div>
                <select class="chosen-select form-control" id="employee_id" name="employee_id" data-placeholder="Выберите пользователя...">
                    <option value="0"> </option>
                    <?
                    if(mycount($this->row_employee) > 0){
                        foreach($this->row_employee as $key => $value){?>
                            <option value="<?=$value['employee_id']?>" <?if($this->row['employee_id'] == $value['employee_id']){echo ' selected';}?>><?=$value['fio']?></option>
                            <?
                        }
                    }?>
                </select>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-sm px-4 btn-outline-success mb-1" onclick="updUserRightItem()">Сохранить</button>
    <button type="button" class="btn btn-sm px-4 btn-outline-danger mb-1" data-dismiss="modal">Закрыть</button>
</div>
<script>
    $(document).ready(function() {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });
    });

    function updUserRightItem(){
        var send_data = $('#form_id').serializeArray();
        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/system/user-right-item-list/mode/upd/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Пользователь успешно добавлен');
                    showUserTable($('#user_right_id').val());
                    $(".modal").modal('hide');
                }
            }
        });
    }
</script>