<?
$this->headTitle('Права');
$this->placeholder('page-header')->set("Права");
?>

<input type="hidden" id="reload_type" name="reload_type">
<input type="hidden" id="user_right_id" name="user_right_id">

<div class="row">
    <div class="col-lg-6">
        <div class="card dcard mb-3" id="card-5" draggable="false" style="">
            <div class="card-header">
                <h5 class="card-title text-120 text-primary-d2">
                    Права
                </h5>
                <div class="card-toolbar">
                    <div class="card-toolbar no-border">
                        <a href="javascript:void(0)" class="card-toolbar-btn btn btn-sm radius-1 btn-outline-success mx-2px" draggable="false" onclick="showModalRight(0)">
                            <i class="fas fa-plus w-2 mx-1px"></i>
                        </a>
                    </div>
                </div>
            </div><!-- /.card-header -->
            <div class="card-body p-0">
                <div class="p-3">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered hover-table" id="user_right_table">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th  style="width: 300px;">Название</th>
                                <th>Код</th>
                                <th></th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?
                            foreach ($this->row as $key => $value){?>
                                <tr>
                                    <td onclick="showUserList(<?=$value['user_right_id']?>, this)" class="text-right">
                                        <?=$value['user_right_id']?>
                                    </td>
                                    <td onclick="showUserList(<?=$value['user_right_id']?>, this)" class="text-left"><?=$value['user_right_name']?></td>
                                    <td onclick="showUserList(<?=$value['user_right_id']?>, this)" class="text-left"><?=$value['user_right_code']?></td>
                                    <td class="text-center">
                                        <a href="#" class="mx-2px btn radius-1 border-2 btn-xs btn-brc-tp btn-light-secondary btn-h-lighter-success btn-a-lighter-success" onclick="showModalRight(<?=$value['user_right_id']?>)">
                                            <i class="fa fa-pencil-alt"></i>
                                        </a>
                                    </td>
                                    <td class="text-center">
                                        <a href="#" class="mx-2px btn radius-1 border-2 btn-xs btn-brc-tp btn-light-secondary btn-h-lighter-danger btn-a-lighter-danger" onclick="delRight(<?=$value['user_right_id']?>, this)">
                                            <i class="fa fa-trash-alt"></i>
                                        </a>
                                    </td>
                                </tr>
                                <?
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div><!-- /.card-body -->
        </div>
    </div>
    <div class="col-lg-4">
        <div id="user_list">

        </div>
    </div>
</div>
<script>
    $(document).ready(function() {

    });
    function delRight(user_right_id, ob){
        if (!confirm('Вы действительно хотите?')) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/system/user-right/mode/del/",
            data:{"user_right_id" : user_right_id},
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Право удалено');
                    $('#user_list').empty();
                    $(ob).closest("tr").remove();
                }
            }
        });
    }
    function showUserTable(user_right_id){
        $("#user_list").load("/system/user-right-item-list/", {user_right_id: user_right_id});
    }

    function showModalRight(user_right_id){
        $('#modal-container').find('.modal-dialog').addClass('modal-sm');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        if(user_right_id > 0){
            $('#modal-header-container').append('Редактирование права');
        }else{
            $('#modal-header-container').append('Добавление права');
        }
        $.ajax({
            type: 'POST',
            url: "/system/user-right-edit/",
            data:{user_right_id: user_right_id},
            async: true,
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $(".modal").modal('show');
    }
    function showModalRightItem(user_right_item_id){
        $('#modal-container').find('.modal-dialog').addClass('modal-sm');
        $("#modal-header-container").empty();
        $("#modal-body-container").empty();
        $('#modal-header-container').append('Редактирование права пользователя');

        var user_right_id = $('#user_right_id').val()
        if(user_right_id == 0){
            alert('Выберите право!');
            return;
        }
        $.ajax({
            type: 'POST',
            url: "/system/user-right-item-edit/",
            data:{
                user_right_id: user_right_id,
                user_right_item_id: user_right_item_id
            },
            async: true,
            success: function(data){
                $("#modal-body-container").html(data);
            }
        });
        $(".modal").modal('show');
    }

    function showUserList(user_right_id, ob){
        $('#reload_type').attr('value', 'all');
        $('#user_right_id').val(user_right_id);
        $('#user_right_table tbody tr').removeClass('selected-td');
        $(ob).closest('tr').addClass('selected-td');
        showUserTable(user_right_id);
    }

    function startReload() {
        if($('#reload_type').val() == 'all'){
            $('.loading-widget').aceCard('reload');
            $('#reload_type').attr('value', '');
        }else if($('#reload_type').val() == 'menu'){
            $('#menu_widget').aceCard('reload');
            $('#reload_type').attr('value', '');
        }
    }

    function stopReload() {
        $('.loading-widget').aceCard('stopLoading');
    }

    $(document).ajaxStart(function() {
        startReload();
    });

    $(document).ajaxStop(function() {
        stopReload();
    });
</script>