<div class="modal-body" id="modal_body">
    <form id="form_id">
        <input type="hidden" value="<?=$this->user_right_id?>" name="user_right_id">
        <div class="form-group">
            <label class="control-label " for="user_right_name">Название</label>
            <input type="text" id="user_right_name" placeholder="Название" class="form-control" value="<?=$this->row['user_right_name']?>" name="user_right_name">
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label class="control-label " for="user_right_code">Код</label>
            <input type="text" id="user_right_code" placeholder="Код" class="form-control" value="<?=$this->row['user_right_code']?>" name="user_right_code">
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-sm px-4 btn-outline-success mb-1" onclick="updUserRight()">Сохранить</button>
    <button type="button" class="btn btn-sm px-4 btn-outline-danger mb-1" data-dismiss="modal">Закрыть</button>
</div>

<script>
    $(document).ready(function() {
        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });
    });

    function updUserRight(){
        var send_data = $('#form_id').serializeArray();
        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/system/user-right/mode/upd/",
            success: function(data){
                if(data.result['status'] == false){
                    bootboxAlert(data.result['error']);
                }
                else{
                    toastSucces('Тип права успешно отредактирован');
                    location.reload();
                }
            }
        });
    }
</script>